### ISSUE TITLE
Freaky sliding window count

### ISSUE THREAD

**Issue by emanueledellavalle** [espertechinc/esper#100]
I experiment a very strange behaviour on sliding window count that I've never noticed before. In a window that contains 4 events, only three are counted. I report the details hereafter. 

Can you please explain if it is the expected behaviour? Otherwise, I think this is a bug.

Let me explain what I did. I create a simple event type

```
create schema Event(
val int
);
```

I put the following two EPL statements that, in my understanding, shall give exactly the same result
```
@Name('Q1') select sum(val) from Event.win:time_batch(4 sec)   ;
@Name('Q2 ') select sum(val) from Event.win:time(4 sec)  output last every 4 sec ;
```

I send the following data

```
Event={val=1}
t=t.plus(1 seconds)
Event={val=1}
t=t.plus(1 seconds)
Event={val=1}
t=t.plus(1 seconds)
Event={val=1}
t=t.plus(1 seconds)
Event={val=1}
t=t.plus(1 seconds)
Event={val=1}
t=t.plus(1 seconds)
Event={val=1}
t=t.plus(1 seconds)
Event={val=1}
t=t.plus(1 seconds)
Event={val=1}
t=t.plus(1 seconds)
```

But the answers are different. Q1 correctly gives 4, while Q2 wrongly gives 3.

Q1 answer is:

```
 At: 2001-01-01 08:00:04.000
    Insert
        Q1-output={sum(val)=4}
At: 2001-01-01 08:00:08.000
    Insert
        Q1-output={sum(val)=4}
```

Q2 answer is:

```
At: 2001-01-01 08:00:04.000
    Insert
        Q2-output={sum(val)=3}
At: 2001-01-01 08:00:08.000
    Insert
        Q2-output={sum(val)=3}
```

**Comment by bernhardttom** [comment]
A time window of 1-second expands to exactly one second of events i.e. 2001-01-01 08:00:00.000 to 2001-01-01 08:00:00.999 inclusive. Send an event at "2001-01-01 08:00:00.000" and move time to "2001-01-01 08:00:01.000" removes the event putting the count to zero --> expected.

**Comment by emanueledellavalle** [comment]
thank you,

Emanuele

--
Emanuele Della Valle, PhD
m. +393389375810
w. http://emanueledellavalle.org
t. @manudellavalle
