### ISSUE TITLE
Reflection warning with Java 9

### ISSUE THREAD

**Issue by gcaplan** [espertechinc/esper#102]
As you're probably aware, the current release is running foul of the new reflection constraints in Java 9. 

It's easy enough to suppress the warning with:

`--add-opens java.base/java.lang=ALL-UNNAMED`

But is there any timeline for updating Esper to run cleanly on Java 9?

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/C:/Users/geoff/.m2/repository/cglib/cglib-nodep/3.2.5/cglib-nodep-3.2.5.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by bernhardttom** [comment]
Changes are in 8.0.0 release.
