### ISSUE TITLE
Time provider not appropriately updated

### ISSUE THREAD

**Issue by ysmartin** [espertechinc/esper#104]
I have found an issue with current_timestamp, which may probably affect other time-related aspects. Not sure if it is a bug or a feature, but it creates somehow confusing behaviours.
The function current_timestamp is supposed to return the "current engine timestamp at the time of expression evaluation". If two events arrive in sequence through a stream, and a statement is consuming events from that stream, the current_timestamp should be evaluated every time an event arrives. This is supposed to be using System.currentTimeMillis() (indeed, I have explicitly added "milli" to the esper.cfg.xml file to make sure that is the case).
However, I am getting the same value of current_timestamp for successive events, processed at different moments (checked with the time of the logs, I know there can be a little difference between when statement is evaluated and when it is logged, but 20 sec is too much, and I simply observe that the current_timestamp is stalled). This does not happen always (it seems to be related to speed in underlying I/O to esper, but I am just guessing). After digging through code, I note that SchedulingServiceSPI only has currentTime updated when a TimerEvent is received by the EPRuntime (which I guess is not happening as often as needed).
Besides, another undesirable effect that also seems to be related. When I try to get ordered events using a time_order window, it works strangely: no event appears at its rstream before the window delay has passed; however, it may be the case that many of those events get an additional delay and are only delivered (in order, but all at once) after many seconds later, whenever the currentTime is advanced and catches all those pending events.

**Comment by bernhardttom** [comment]
All the time advancing is under application control. See the doc link http://esper.espertech.com/release-7.0.0/esper-reference/html_single/index.html#api-controlling-time
