### ISSUE TITLE
Provide an efficient way to measure number of context partitions

### ISSUE THREAD

**Issue by rtkcthomson** [espertechinc/esper#105]
The `com.espertech.esper.client.context.EPContextPartitionAdmin` interface provides two methods to access the context partition information:

```
   public ContextPartitionCollection getContextPartitions(String contextName, ContextPartitionSelector selector);
   public Set<Integer> getContextPartitionIds(String contextName, ContextPartitionSelector selector);
```

Both of these methods create collections (`TreeMap`, `HashMap` for `getContextPartitions` and `HashSet` for `getContextPartitionIds`) that can have an impact on the heap as well as CPU when a large number of context partitions exist.

This is an improvement request to expose a method on EPContextPartitionAdmin to get the current count of partitions that is both memory and CPU time efficient for monitoring purposes.

**Comment by bernhardttom** [comment]
in beta-2
