### ISSUE TITLE
Would it be possible to support arrays in the cast funtion

### ISSUE THREAD

**Issue by serfervid** [espertechinc/esper#107]
When trying to cast to an array(e.g. `cast(myArrayField, java.lang.String[])`) in an epl query I get the following error:
`com.espertech.esper.client.EPStatementSyntaxException: Incorrect syntax near '[' expecting a closing parenthesis ')' but found a left angle bracket '['`

Would it be possible to support the cast to an array?

**Comment by bernhardttom** [comment]
is part of 8.0.0
