### ISSUE TITLE
Determination of overloaded method applicability with varargs 

### ISSUE THREAD

**Issue by ysmartin** [espertechinc/esper#108]
Have a class that provides several methods with the same name, one of them with a single varargs argument, and the rest with fixed 2, 3, etc. arguments of the same type. For instance, this is the case of [Guava's `Iterable.concat` methods](http://google.github.io/guava/releases/24.1-jre/api/docs/com/google/common/collect/Iterables.html): 

- [concat(Iterable<? extends T>... inputs)](https://github.com/google/guava/blob/e24fddc5fff7fd36d33ea38737b6606a7e476845/guava/src/com/google/common/collect/Iterables.java#L417)
- [concat(Iterable<? extends T> a, Iterable<? extends T> b)](https://github.com/google/guava/blob/e24fddc5fff7fd36d33ea38737b6606a7e476845/guava/src/com/google/common/collect/Iterables.java#L432) 
- [concat(Iterable<? extends T> a, Iterable<? extends T> b, Iterable<? extends T> c)](https://github.com/google/guava/blob/e24fddc5fff7fd36d33ea38737b6606a7e476845/guava/src/com/google/common/collect/Iterables.java#L449)
- [concat(Iterable<? extends T> a, Iterable<? extends T> b, Iterable<? extends T> c, Iterable<? extends T> d)](https://github.com/google/guava/blob/e24fddc5fff7fd36d33ea38737b6606a7e476845/guava/src/com/google/common/collect/Iterables.java#L471)

Try to invoke of of the first methods from within an EPL `select` clause (maybe this also happens in other situations), e.g.
````
Iterables.concat( aCollection, anotherCollection )
````
**Expected behaviour:** the fixed 2-argument method is invoked. As per the [Java Language Specification 15.12.2](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12.2), overload resolution is first performed "without (...) the use of variable arity method invocation"

**Observed behaviour:** the varargs method is invoked. Even though EPL is not Java, it would be expected to exhibit a Java-language compatible behaviour.

**Comment by bernhardttom** [comment]
Changes are in 8.0.0 release.
