### ISSUE TITLE
Coercion from Interface to Object

### ISSUE THREAD

**Issue by ysmartin** [espertechinc/esper#109]
JavaClassHelper.isSubclassOrImplementsInterface https://github.com/espertechinc/esper/blob/58059d8ba3c3818b83c6ca438d559b0c7fbcfbef/esper/src/main/java/com/espertech/esper/util/JavaClassHelper.java#L1011 does not work as appropriate when `extendorOrImplementor` is an interface and `extendedOrImplemented` is `java.lang.Object`.

Expected behaviour: return `true`, as the type `Object` is a supertype of any interface, as per [JLS 4.10.2](https://docs.oracle.com/javase/specs/jls/se7/html/jls-4.html#jls-4.10.2)

Observed behaviour: it returns `false`

The behaviour of this method should be compatible with Java assignment, at least with respect to this issue. As a consequence of that, in some cases (not sure why not always) I have not been able to properly pass attributes to a method from EPL without introducing explicit casts to Object (however, this issue may manifest in other situations where this workaround may not be applicable).

**Comment by bernhardttom** [comment]
Changes are in 8.0.0 release.
