### ISSUE TITLE
Issue Parsing Pound Symbol(#) on macOS

### ISSUE THREAD

**Issue by yguy08** [espertechinc/esper#110]
Using a simple statement that works on windows has issues on my mac. Look's to be an issue parsing the pound symbol which pretty much eliminates any useful esper statements. 

Here's the exception esper throws:
Exception in thread "main" com.espertech.esper.client.EPStatementSyntaxException: Unexpected end-of-input near 'Tick' at line 1 column 31, please check the from clause [@Name(SelectAll) select * from Tick#length(5);]

May be an issue with antlr:
LexerNoViableAltException('#')

**Comment by ysmartin** [comment]
A workaround while Esper team attends this issue: to the best of my knowledge, in most cases you can also refer to windows with a dot + window namespace + colon instead of a hash:
````[@name(SelectAll) select * from Tick.win:length(5);]````

**Comment by yguy08** [comment]
@ysmartin thanks for the workaround. dot + window + colon works instead of a hash.

**Comment by bernhardttom** [comment]
Please test on MacOS with the corrected name annotation.
