### ISSUE TITLE
String formatting of arrays in audit traces

### ISSUE THREAD

**Issue by ysmartin** [espertechinc/esper#111]
When audit mode is active for a statement, expressions and event properties are frequently rendered as a string. This is done according to the respective implementation of the toString method. As it is known, the result of toString is not particularly explanatory in the case of Java arrays, which default to the implementation provided by Object (which consists into the class name plus the identity hash). Implementations of java.util.Collection, on the other hand, often provide a much more useful implementation of toString which reveals its contents. The utility methods Arrays.toString and Arrays.deepToString try to mimic this content if the developer prefers it to the the default implementation of Java array.

However, in Esper audit traces, this is not possible, as it is encapsulated by the implementation of the audit functionality. The use of collections is not always possible or desirable. It would be nice if Esper would instead use the self explanatory version, or let the user have it configured. (This is a feature request, not a bug).

**Comment by bernhardttom** [comment]
The change is part of 8.0.0
