### ISSUE TITLE
kafka Adapter eventlist

### ISSUE THREAD

**Issue by trumanliu** [espertechinc/esper#112]
In my situation,each kafka message is a json string which can be parsed as an arraylist of events. I tried to return arrayList of my event in the VALUE_DESERIALIZER_CLASS_CONFIG class. In the com.espertech.esper.filter.EventTypeIndex.matchType() method , the arrylist type doesn't match my event type. I changed com.espertech.esper.core.service.processEvent() method to check if the event is instance of Collection and got it works. Is this the right approach ? Shoud I submit a pull request ?

**Comment by bernhardttom** [comment]
Definitely not. Support event types are Map/Object-Array/Class/DOM.
