### ISSUE TITLE
"Map" implementations should be used in the case of "unnested hash-with-preallocate or category contexts"

### ISSUE THREAD

**Issue by murat-lacework** [espertechinc/esper#114]
I am creating this issue as suggested by Thomas Bernhardt in the following thread from the esper usage forum:  https://groups.google.com/forum/#!topic/esper-usage/Q1SA3eB6DSk

I have copied the e-mail thread for the issue below:

This is definitely a bug. The "MultiPerm" implementation is for the cases when then number of context partitions is fixed. This is the case of unnested hash-with-preallocate or category contexts. The "Map" implementations should be used instead. The bug may have been introduced when there were changes to computing the context partition id. 
Please open a Github issue for tracking.
The workaround is to use a nested context. 

Best regards,
Tom

On Monday, May 28, 2018 at 3:59:03 PM UTC-4, murat.bog@lacework.net wrote:
Hi,

Consider the following test case using overlapping contexts with distinct events for initiation condition:

The runtime is injected the following events:
TestEvent
InitiateContextEvent
TerminateContextEvent
Each event type has a  contextId (of type string) field.   

In the test case, each new context is generated with a unique contextId. 

The TestEvent has one other string type field named kind (of type string).

The InitiateContextEvent and TerminateContextEvent event types are injected to control context lifecycle using the following statement:

create context TestContext
  initiated by distinct(contextId) InitiateContextEvent as ice
  terminated by TerminateContextEvent(contextId = ice.contextId)

A number of TestEvents are injected for each context in between associated InitiateContextEvent and TerminateContextEvents.  The TestEvent events in a context are aggregated using the following aggregation statement aggregation statement

context TestContext
select kind, count(*)
from TestEvent
where contextId = context.ice.contextId
group by kind
output snapshot when terminated

What I have noticed is that the AIRegistryAggregationMultiPerm class used in this test case has a services field that is of type ArrayWrap<AggregationService>.   As each context is initiated and terminated, the assignService and deassignService methods of this class is called with a serviceId argument that starts incrementing by 1 starting from 0.   Thus the size of the underlying array of the services field can keep growing (up to INT.MAX_VALUE) even though the total number of contexts that may exist in parallel can be limited.   

Over time, this could result in too much memory being allocated to this array even though most of its elements will be set to null at any given time.

**Comment by bernhardttom** [comment]
Bug fix is part of 8.0.0
