### ISSUE TITLE
Escape characters for schema package names do not work

### ISSUE THREAD

**Issue by jheusser** [espertechinc/esper#12]
If a package name contains a keyword, then you can't define a schema for it:
```
create schema OrderEvent as com.tld.app.common.`order`.OrderEvent;
```
Does not find the package (it seems it looks for it with the backtick). Without the escaping it won't compile with error:
_Caused by: com.espertech.esper.client.EPStatementSyntaxException: Incorrect syntax near '.' expecting end-of-input but found a dot '.' at line 5 column 52_

**Comment by bernhardttom** [comment]
Can't reproduce with version 5.2. Always please provide the full stack trace.
