### ISSUE TITLE
The function determineTableAccessNodes  has redundant codes in StatementLifecycleSvcImpl.java  

### ISSUE THREAD

**Issue by sinwaj** [espertechinc/esper#120]
Dear sir,
   I find the codes of the function determineTableAccessNodes  in StatementLifecycleSvcImpl.java  are allmost same as the following.In my opition ,if some redundant codes are deleted ,the Class will be better.
   Thanks,Best Regards..

   The redundant codes as following:
   
// Determine table access nodes
        Set<ExprTableAccessNode> tableAccessNodes = determineTableAccessNodes(statementSpec.getTableExpressions(), visitor);
        new HashSet<ExprTableAccessNode>();
        if (statementSpec.getTableExpressions() != null) {
            tableAccessNodes.addAll(statementSpec.getTableExpressions());
        }
        if (visitor.getDeclaredExpressions() != null) {
            ExprNodeTableAccessVisitor tableAccessVisitor = new ExprNodeTableAccessVisitor(tableAccessNodes);
            for (ExprDeclaredNode declared : visitor.getDeclaredExpressions()) {
                declared.getBody().accept(tableAccessVisitor);
            }
        }
        for (ExprSubselectNode subselectNode : visitor.getSubselects()) {
            if (subselectNode.getStatementSpecRaw().getTableExpressions() != null) {
                tableAccessNodes.addAll(subselectNode.getStatementSpecRaw().getTableExpressions());
            }
        }

**Comment by bernhardttom** [comment]
ok, the refactoring will be part of version 8 which should be done soon, thank you

**Comment by bernhardttom** [comment]
change will be in 8.0.0

**Comment by sinwaj** [comment]
great
