### ISSUE TITLE
Filter expression with constant variable does not trigger

### ISSUE THREAD

**Issue by jheusser** [espertechinc/esper#121]
The following code does **not** trigger when receiving a matching `Event` on latest Esper version:
```
create constant variable SomeType x = ..;
select * from Event(field = x);
```

while the following code does trigger on a matching `Event`:

```
create variable SomeType x = ..;
select * from Event(field = x);
```

where the only difference is that variable `x` is `constant` or not, with same actual value for `x`.

I'll submit a minimal test case for it.

**Comment by bernhardttom** [comment]
No code provided to reproduce. Please reopen once you have posted the code.

**Comment by jheusser** [comment]
@bernhardttom Please see following gist with test code https://gist.github.com/jheusser/b894faefd5021e4ad282f400b99fae24

Both tests are identical but one creates a non-constant variable, the other a constant one. The first test passes (event is received), the second test fails (event not received).
