### ISSUE TITLE
Configuration for timer thread to trigger and emit events when using external time source

### ISSUE THREAD

**Issue by yangguang760** [espertechinc/esper#124]
I found that when using external time source, the thread who send CurrentTimeEvent or CurrentTimeSpanEvent is not the thread who invoke updateListener(). 
The configuration of timer thread is closed as 
```
<threadpool-timerexec enabled="false" num-threads="1"/>
```
Are there any way to make the threads who send TimeEvent and who invoke the updateListener the same one?
Thx.

**Comment by bernhardttom** [comment]
The timer thread always delivers to listeners unless you have some other threading options enabled in the configuration such as outbound threading.
