### ISSUE TITLE
Esper7.1.0: Event was inserted into stream, but not fired to listener

### ISSUE THREAD

**Issue by jdnull** [espertechinc/esper#125]
Most situation in my application, events were inserted into stream and fired to listener well. But there happened extremely few situation that events were inserted into stream but not fired to listener. I was trying to reproduce such things but failed.

My epl was simply composed such as "context myCtx select * from MyEvent".

I use 'audit' annotation, and find 'Statement stmt_1 stream MyEvent inserted', but the listener not triggered.

Is there any debug method for such situation?

Thx!

**Comment by raguessner** [comment]
Please write a test class that reproduces the issue and attach it.

**Comment by jdnull** [comment]
I'm sorry that I can't reproduce using any test class, such situation occasionally happened (only twice in last two month), I can't figure out how this would happen.

From the log file, there may be a clue that the only two happened cases all have such log:

> .createView No new views created, dumping stream... com.espertech.esper.view.ZeroDepthStreamNoIterate@XXXXX

**Comment by raguessner** [comment]
I would not think that the message has any relationship. I would check the transport and threading making sure there is no loss.

**Comment by bernhardttom** [comment]
No information provided how to reproduce
