### ISSUE TITLE
Shows warning message related to CompileException in Esper

### ISSUE THREAD

**Issue by echoshearer** [espertechinc/esper#126]
When I try to insert events into a new stream , it appears the following warning" Failed to code-generate for statement 'FILTER_RISK_RULE_BY_ACCOUNT_1' result-set-processor requestor-class 'ResultSetProcessorFactoryFactory' (invalid code follows, falling back to regular evaluation): Failed to compile generated code
code-in-error (please provide with issue reports):"
The stack log shows "Assignment conversion not possible from type "com.espertech.esper.client.EventBean" to type "com.risk.model.RiskRule"。 The following is my EPL
“on RiskCheckContext rc
insert into RiskContext (riskCheckContext,riskRule,riskRuleCount)
select
rc as riskCheckContext,
r as riskRule,
count(*) as riskRuleCount
from RiskRuleWindow as r”

is anything wrong?

**Comment by raguessner** [comment]
Could you provide a test class?

**Comment by bernhardttom** [comment]
No information provided how to reproduce.
