### ISSUE TITLE
"Output after time_period" with external timer

### ISSUE THREAD

**Issue by mundus08** [espertechinc/esper#13]
In my scenario the output “after time_period” option does not work with external timer.
The statement
      EPStatement cepStatement3a = cepAdm_.createEPL(
              " insert into stream1                               " +
              " select minby(bid).bid                as ibid   ,  " +
              "        minby(bid).dtBid.getMillis()  as idbid  ,  " +
              "        maxby(bid).bid                as abid   ,  " +
              "        maxby(bid).dtBid.getMillis()  as adbid  ,  " +
              "        current_timestamp             as ts     ,  " +
              "        'win1'                        as winsize   " +
              "   from StockTick.win:time(60 sec)                 " +
//            "   output snapshot every 10 sec                    " +
//            "   output after 100 events snapshot every 10 sec   " +
              "   output after 60 sec snapshot every 10 sec        " +
works without "after option" and with option “after n events"
With option “after 60 sec” no event  is produced

**Comment by bernhardttom** [comment]
Provide a test class?

**Comment by mundus08** [comment]
I uploaded a repro to
  https://www.dropbox.com/sh/uje4j3vrappyy6l/AAArMYvlaet0qboOG1cK0saBa?dl=0
Important: the problem only occurs if the events are in the past
      long lStart = new DateTime(2015,7,24,8,0).getMillis();

**Comment by bernhardttom** [comment]
Set a time before creating the statements.
