### ISSUE TITLE
Back pressure when group by groups are too many

### ISSUE THREAD

**Issue by XiaTianliang** [espertechinc/esper#137]
We use esper to aggregate log events in fixed time window and then send to DB, when a large amount of events are drained into esper(for example consuming kafka log from the beginning), the GC is very terrible.  It seems that when group by groups is vary large and the time window is not short enough, the esper should hold the results in memory which makes GC difficult. Is there a way to block the send thread(send event to esper) or trigger the listener to flush out results according to the num of group by categories.
the event and epl  looks like:
``````java
class Event {
    private String name;
    private int count;
    private long timestamp;
    // setter getter
}

//user define function
public static long truncate_ts(long ts, long period) {
    return ts / period * period;
}

create context one_minute start @now end after 10 sec;

context one_minute
select name, truncate_ts(timestamp, 10000) as timestamp, sum(count) from event
group by name, truncate_ts(timestamp, 10000)
output snapshot when terminated;
``````
we have tried adjusting the inbound threading settings and using the back pressure strategy in inbound, however the sending process is not time costly, events are still drained into the engine.

**Comment by bernhardttom** [comment]
The above statement retains in memory a row per event because "truncate_ts(timestamp, 10000)" depends on the event. If you can change to "truncate_ts(last(timestamp), 10000)" the query becomes fully-aggregated and the runtime only needs to retain a row per name.

The question is also how time advances when consuming kafka log from the beginning. In the case that the application does not advance time or uses system time, the "after 10 sec" is 10 seconds, it can be a very large amount of events. The solution is to advance time or to instead do something like 10 seconds or 1000 events whichever occurs first.

**Comment by XiaTianliang** [comment]
Thanks for answering my question so detailed. 

In fact, the log events are aggregated by truncated event timestamp then write to a time series database as show in the picture below:
<img width="601" alt="esper" src="https://user-images.githubusercontent.com/11326360/50645929-bca2f380-0faf-11e9-90ab-5b2e07bfc663.png">
Truncate_ts(last(timestamp), 10000) will aggregate the events come in the the same time interval with respect to the wall clock, this can not fulfill the needs.

Advancing the runtime time with external time event may cause some problems because the log events could be stored at many kafka topics and partitions, the order is not well guaranteed. The log timestamp can also be wired sometimes.

The third option sounds good, how to control the statement triggered with both time period and event count ? Use nest context ?  Can you please provide some example ?

**Comment by bernhardttom** [comment]
```
create schema EndContext();
create context one_minute start @now end EndContext;
context one_minute insert into EndContext select * from pattern[timer:interval(10)];
context one_minute insert into EndContext select null from event having count(*) = 1000;
```
