### ISSUE TITLE
variable method invocation threading issue

### ISSUE THREAD

**Issue by andyflury** [espertechinc/esper#14]
Hi

Invoking methods on variables based on events that are sent from a different thread does not work.

Please see Java test case below.

Thanks

    @Test
    public void testThreadingWithVariables() throws Exception {

        Configuration config = new Configuration();
        config.addEventType("Signal", Signal.class);
        config.addVariable("stuffDoer", StuffDoer.class, null);

        final EPServiceProvider epService = EPServiceProviderManager.getDefaultProvider(config);
        final EPRuntime epRuntime = epService.getEPRuntime();

        StuffDoer stuffDoer = new StuffDoer();
        epRuntime.setVariableValue("stuffDoer", stuffDoer);

        EPAdministrator epAdministrator = epService.getEPAdministrator();

        EPStatement epStatement = epAdministrator.createEPL("select stuffDoer.doStuff() as value from Signal");

        final CountDownLatch latch = new CountDownLatch(2);
        final List<Double> values = new ArrayList<Double>();

        epStatement.setSubscriber(new Object() {

            public void update(final Map<?, ?> event) {

                System.out.println(event);

                Double value = (Double) event.get("value");
                values.add(value);
                latch.countDown();
            }

        });

        epRuntime.sendEvent(new Signal());

        // Test passes when sending events from the same thread
        //         epRuntime.sendEvent(new Signal());

        // and fails if events are sent from a different thread
        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.execute(new Runnable() {
            public void run() {
                epRuntime.sendEvent(new Signal());
            }
        });

        latch.await();

        Assert.assertEquals(2, values.size());
        Assert.assertNotNull(values.get(0));
        Assert.assertNotNull(values.get(1));

        if (epService != null) {
            epService.destroy();
        }
    }

    static public class StuffDoer {

        public Double doStuff() {
            return 3.0;
        }

    }

    static public class Signal {

    }

**Comment by bernhardttom** [comment]
thanks for the test. The bug fix will be in version 5.3
