### ISSUE TITLE
Cannot get create schema statement to work following upgrade to 8.0.0

### ISSUE THREAD

**Issue by simonmarshall** [espertechinc/esper#140]
Hi guys, we're looking at upgrading to 8.0.0.  

We create event schemas on-the-fly, and need to continue to do so.  In earlier versions, we did this via ConfigurationOperations.addEventType(), getting the ConfigurationOperations instance via the service provider's EPAdministrator.  It seems in 8.0.0 that ConfigurationCommon.addEventType() only works if it is called before getting a runtime via EPRuntimeProvider.getRuntime().  However, we cannot get an equivalent "create map schema" statement to work.  The statement itself is deployed successfully, but a "select" statement on that event fails to compile due to it being an unknown event.  I've attached a unit test with 4 test cases (and their output when run locally for the 3 tests that fail):

[EsperCreateSchema.zip](https://github.com/espertechinc/esper/files/2760259/EsperCreateSchema.zip)

- addEventTypeBeforeGetRuntime(): add the schema via ConfigurationCommon.addEventType() before getting a runtime via EPRuntimeProvider.getRuntime() then add a select statement.  No surprises that this works OK (and if I add a listener and send some data I can verify all is working).

- addEventTypeAfterGetRuntime(): add the schema via ConfigurationCommon.addEventType() after getting a runtime via EPRuntimeProvider.getRuntime() then add a select statement.  Select statement deployment fails due to unknown event.  Maybe not surprising this fails in 8.0, even if (1) a similar flow works in earlier versions, and (2) compilation succeeded.

- theCreateStatementWorksSelectStatementFails(): add the schema via a create statement after getting a runtime via EPRuntimeProvider.getRuntime() then add a select statement.  Select statement compilation fails due to unknown event.  I would expect this to succeed.  Sanity code suggests the runtime deployment service knows about the statement, but the runtime event service doesn't know about the event.

- addEventTypeCreateStatementFails(): add the schema via a create statement after getting a runtime via EPRuntimeProvider.getRuntime() but also add the schema via ConfigurationCommon.addEventType() for future compilation purposes, then add a select statement.  I wondered if this would solve the compilation issue of theCreateStatementWorksSelectStatementFails(), since the compiler takes the configuration via CompilerArguments.  Interestingly, select statement deployment, not compilation, fails due to unknown event.

I've tried playing with modules, but it seems to make no difference.

So, the question is, how do we create schemas on-the-fly with 8.x?

**Comment by bernhardttom** [comment]
All dynamic event types come alive using "create schema".
The access modifier defines whether an event type is visible within the EPL module only or also to other modules.
See [access modifiers](http://esper.espertech.com/release-8.0.0/reference-esper/html_single/index.html#apicompiler-concepts-accessmodifier)
Sets a default access modifier or @public.
See [migrating](http://www.espertech.com/2018/10/23/esper-8-migrating-step-by-step-for-existing-applications/)
