### ISSUE TITLE
Identifier escaping when using "new" not removing backticks

### ISSUE THREAD

**Issue by TAKeanice** [espertechinc/esper#141]
I found that I cannot create a named window which has reserved keywords, spaces or dots in it, because it is not possible to escape it. The grammar for the create window clause starts like this:
```
`createWindowExpr
	:	CREATE WINDOW i=IDENT`
```
which says "i" must be an identifier, but "IDENT" is defined as only letters, numbers or dollar signs. The  exception thrown by the compiler (esper 8) is `expecting an identifier but found TICKED_STRING_LITERAL`.

**Comment by bernhardttom** [comment]
Named windows, tables, expressions, event types, variables etc. are not allowing backticks as they are identifiers. There is no change planned to allow backticks for these.

The "new" keyword should indeed remove backticks.

**Comment by TAKeanice** [comment]
It would not be too difficult to incorporate backticks for some of the cases into the grammar. At least, it should be documented, as of the date I created the issue, it was very unclear where backticks can be used. It sounded like any identifier could be escaped, which would be a sensible choice for automatically created queries or queries made from user input.

**Comment by bernhardttom** [comment]
can you please create a new ticket?
