### ISSUE TITLE
Can not use Count-Min sketch with Apache avro as default event representation

### ISSUE THREAD

**Issue by RacekM** [espertechinc/esper#143]
Hi I am trying to count topK on some attribute from stream. When I try it without setting default event representation to Apache Avro then everything works.
But with avro it breaks (NullpointerException).
`              config.getCommon().getEventMeta().setDefaultEventRepresentation(EventUnderlyingType.AVRO);
`

```
create schema StockTick(symbol string, price long);

create table TopKTable (wordsCnt countMinSketch({
  epsOfTotalCount: 0.000002,
  confidence: 0.999,
  seed: 38576,
  topk: 3
}));

//@EventRepresentation(objectarray)
into table TopKTable
select countMinSketchAdd(symbol) as wordsCnt
from StockTick;

insert into NumericStatsEvent
select sum(price) as price
from StockTick#time_batch(10 sec);

@Name('Out')
on NumericStatsEvent
insert into ResultEvent
select delete NumericStatsEvent.price as price ,
          wordsCnt.countMinSketchTopk() as topK
from TopKTable
```

I figured out that adding "@EventRepresentation(objectarray)" annotation to "into table ..." statement helps with NullPointerException, but there is still problem with mapping "CountMinSketchTopK[]" to avro attribute. I implemented custom TypewWidenerSPI (with "TypeRepresentationMapper" and "ObjectValueTypeWidenerFactory") from "CountMinSketchTopK[]" to java map and then the mentioned EPL module finally compiled but when it is deployed then instead of using the implemented widener its inserting "CountMinSketchFrequency" entities into map.

K is for example 3
Result ->`ResultEvent: {"price": 3, , "topK": [CountMinSketchFrequency{frequency=3, value=}]}`
Expecting ->   `ResultEvent: {"price": 3, "topK": {"randomString": 10, ... }}
`

Did I missed something or is there any way how to do it ?

EDIT
It seems to works the "CountMinSketchFrequency" is there because the corresponding attribute is in all incoming events empty (attribute in GenericRecord is empty string). Is there any way how to force using only "CountMinSketchTopK". Or is it possible to implement it easier?

**Comment by bernhardttom** [comment]
Post the full exception stack trace please. Also provide a test class if you can please.

**Comment by RacekM** [comment]
[error.txt](https://github.com/espertechinc/esper/files/2900343/error.txt) This is the stacktrace of exception which occured when I commented `@EventRepresentation(objectarray)`. The EPRuntime is configured to use Avro as default event representation `config.getCommon().getEventMeta().setDefaultEventRepresentation(EventUnderlyingType.AVRO);`
When the default event representation is used then everything works even without using mentioned annotation.

But my main issue is how to use result of ` wordsCnt.countMinSketchTopk() as topK` with Avro as default event representation. I am trying to convert it into Map<String, Long> (value: frequency) but sometimes instead of  "CountMinSketchTopK[]" it returns "CountMinSketchFrequency[]". Which is totally different type and then I need another custom "TypeWidenerSPI" .

Is there easier way how to use result of `countMinSketchTopk()` with avro as default event representation? 

Thank you
