### ISSUE TITLE
Occasional crashes when compiling queries with beans which have super types

### ISSUE THREAD

**Issue by steven509** [espertechinc/esper#145]
```
esper common version: 8.1.0
esper runtime version: 8.1.0
esper compiler version: 8.1.0
```

When adding models with super types using `addEventType(Class eventClass)` and then compiling a query, sometimes this will fail. It seems to be caused by a mismatch in the name of the super type. When adding the event class with `addEventType(Class eventClass)` the name is the simple name of the class. However later on the super types get added in `EventTypeRepositoryBeanTypeUtil` using the name of the class, instead of the simple name.

Is there a correct way to be adding these models without having the use the full quantified name everywhere?

**Comment by bernhardttom** [comment]
Provide a test class please.

**Comment by steven509** [comment]
This issue can be closed as I've found the solution to my problem now. In my case the super types weren't always being added before the subtypes.

Many thanks
