### ISSUE TITLE
how can I get the value of the property `name` using avro event type?

### ISSUE THREAD

**Issue by huansoo** [espertechinc/esper#147]
Firstly, I create an avro event, then I want to search the event, which events's name equals "name2",
the epl is below:
String epl0 = "create avro schema User as (name string, id int, age int);";
String epl2="@EventRepresentation('avro') @Audit @name('epl2') select * from User p where p.name='name2';";
and I have add listeners to epl2;    when I sended GenericRecord data to the esper engine, which events's property `name` equals "name2", but I got no event to the updateListeners,  so how can I write the epl2, to filter the event,  which property `name` equals "name2"

**Comment by raguessner** [comment]
sample follows ....

`        String epl = "@buseventtype @public create avro schema User as (name string, id int, age int);\n" +
                "@name('out') select * from User(name='Joe');\n";
        EPRuntime runtime = EPRuntimeProvider.getDefaultRuntime();
        EPDeployment deployment = compileDeploy(runtime, epl);

        AvroSchemaEventType eventType = (AvroSchemaEventType) runtime.getEventTypeService().getEventType(deployment.getDeploymentId(), "User");
        Schema schema = (Schema) eventType.getSchema();

        SupportUpdateListener listener = new SupportUpdateListener();
        EPStatement statement = runtime.getDeploymentService().getStatement(deployment.getDeploymentId(), "out");
        statement.addListener(listener);

        GenericRecord record = new GenericData.Record(schema);
        record.put("name", "Joe");
        runtime.getEventService().sendEventAvro(record, "User");

        System.out.println("Received: " + listener.assertOneGetNewAndReset().get("name"));
`

**Comment by huansoo** [comment]
tks for your reply,  I have already got all the property of the User ,but now I want to fetch the property name only,how can I write the epl, I have trid the following, and I got the name's value is null
String epl = "@name('out') select name from User(name='Joe');\n";

**Comment by huansoo** [comment]
tks for your reply, I have already got all the property of the User ,but now I want to fetch the property name only,how can I write the epl, I have trid the following, and I got the name's value is null
String epl = "@name('out') select name from User(name='Joe');\n";
In my project, I want to aggregate two avro events with the same event property value, eg 
String epl="select  u.name, u.id, b.id, b.occuption from User(age>30) as u, Bussiness(age>40) as b where u.name=b.name"
in a javabean type event, I know how to do this , but in avro event ,I have trid the above epl, and I didn't get the wanted results

**Comment by bernhardttom** [comment]
Avro behaves the same as javabean. If you think that is now the case please provide a test class.
