### ISSUE TITLE
can Esper support nested global expression

### ISSUE THREAD

**Issue by zhucj1981** [espertechinc/esper#151]
for example
create expression A {V=>V.value1+V.value2}
create expression B {V=>V.value1-V.value2}

//nest expression call
create expression C {V=>A(V)+B(V)}

**Comment by raguessner** [comment]
I tried it online and success.

create schema StockTick(value1 double, value2 double);
create expression A {V=>V.value1+V.value2};
create expression B {V=>V.value1-V.value2};
create expression C {V=>A(V)+B(V)};
@Name('Out') select C(e) from StockTick as e;

StockTick={value1=20.5,value2=20.5}

**Comment by zhucj1981** [comment]
Thank you.
