### ISSUE TITLE
Unable to use escaped property names in join with window expression

### ISSUE THREAD

**Issue by vndzzz** [espertechinc/esper#158]
Currently it is impossible to use escaped property names in external windows with join expressions.
Example:
```
   select key, `$value$`
       from KeyValue w, TestSchema#lastevent t
   where w.`$value` = t.value1
```
Where KeyValue is an external window with following schema:
```create schema KeyValueEvent(key integer, `$value$` string)```

Compiling such expression returns error `Failed to find property '$value$'`
Possible cause of it may be a bug in [ExprIdentNodeImpl.java](https://github.com/espertechinc/esper/blob/release_8.1.0/common/src/main/java/com/espertech/esper/common/internal/epl/expression/core/ExprIdentNodeImpl.java#L185), because in the next line it is tried to find a property which is already unescaped.

**Comment by raguessner** [comment]
You are missing a '$'. Works online.

```
create schema KeyValue(key integer, `$value$` string);
create schema TestSchema(value1 string);
select key, `$value$`
       from KeyValue#keepall w, TestSchema#lastevent t
   where w.`$value$` = t.value1

```
