### ISSUE TITLE
Destroying and re-restarting statement with same name stops reporting "statementName" in metrics for statement reported by Engine

### ISSUE THREAD

**Issue by sumitjha4321** [espertechinc/esper#159]
Say a statement is started and both engine and statement metrics is enabled.  
Now if we destroy that statement and re-create a new statement with same statement query and same name, the metrics reported by engine no longer container the statement name.

Below is code for better clarification.

1. Engine Configs

        Configuration engineConfig = new Configuration();

        engineConfig.getEngineDefaults().getLogging().setEnableExecutionDebug(true);
        engineConfig.getEngineDefaults().getThreading().setListenerDispatchPreserveOrder(false);
        engineConfig.getEngineDefaults().getLogging().setEnableQueryPlan(false);
        engineConfig.getEngineDefaults().getExecution().setPrioritized(true);
        engineConfig.getEngineDefaults().getLogging().setEnableTimerDebug(false);
        engineConfig.getEngineDefaults().getMetricsReporting().setEnableMetricsReporting(true);
        engineConfig
                .getEngineDefaults()
                .getMetricsReporting()
                .setEngineInterval(5000);
        engineConfig
                .getEngineDefaults()
                .getMetricsReporting()
                .setStatementInterval(5000);

2. Add listener for statement metrics.

        String statementMetrics = "select * from com.espertech.esper.client.metric.StatementMetric";

        epService.getEPAdministrator().createEPL(statementMetrics, "statement-metrics")
                .addListener(new UpdateListener() {
                    @Override
                    public void update(EventBean[] newEvents, EventBean[] oldEvents) {
                        for (EventBean eventBean : newEvents){

                            StatementMetric statementMetric = (StatementMetric) eventBean.getUnderlying();

                            System.out.println(gson.toJson(statementMetric));
                        }
                    }
                });

3. Register a "monitor_statement" statement.

        String statement = "select * from TemperatureEvent";
        String statementName = "monitor_statement";
        epService.getEPAdministrator().createEPL(statement, statementName)
                .addListener(new UpdateListener() {
                    @Override
                    public void update(EventBean[] eventBeans, EventBean[] eventBeans1) {
                        // process alerts
                    }
                });

Statement metrics are reported fine at this point.

>{"timestamp":1559219847744,"statementName":"statement-metrics","cpuTime":322000,"wallTime":254330,"numInput":5,"numOutputRStream":0,"numOutputIStream":5,"engineURI":"default"}{"timestamp":1559219847744,"statementName":"monitor_statement","cpuTime":87000,"wallTime":74379,"numInput":1,"numOutputRStream":0,"numOutputIStream":1,"engineURI":"default"}

Now if the "monitor_statement" statement is destroyed and re-created with same name, statement metrics for it no longer containers the "statementName" field.

Below is helper method to destroy and re-create "Test" statement with same name.

        @Scheduled(fixedDelayString = "10000", initialDelayString = "10000")
          public void helper() throws Exception {
        
        
                EPStatement statement = epService.getEPAdministrator().getStatement("monitor_statement");
            
                // destroy the statement
                statement.destroy();
                Thread.sleep(3000);
              
                // re-create statement with same name
                  String statement = "select * from TemperatureEvent";
        String statementName = "monitor_statement";
        epService.getEPAdministrator().createEPL(statement, statementName)
                .addListener(new UpdateListener() {
                    @Override
                    public void update(EventBean[] eventBeans, EventBean[] eventBeans1) {
                        // process alerts
                    }
                });

Now the statement metrics reported by engine for "monitor_statement" no longer contains the 
"statementName" field.

>{"timestamp":1559219862746,"statementName":"statement-metrics","cpuTime":91000,"wallTime":66644,"numInput":2,"numOutputRStream":0,"numOutputIStream":2,"engineURI":"default"}
{"timestamp":1559219862746,"cpuTime":202000,"wallTime":158649,"numInput":3,"numOutputRStream":0,"numOutputIStream":3,"engineURI":"default"}

Notice the "statementName" field is missing in the metrics reported by engine.

**Comment by bernhardttom** [comment]
test against a recent version.

**Comment by sumitjha4321** [comment]
@bernhardttom 
checked with the latest version from maven central


<dependency>
    <groupId>com.espertech</groupId>
    <artifactId>esper</artifactId>
    <version>7.1.0</version>
</dependency>


Still facing same issue.

**Comment by bernhardttom** [comment]
https://mvnrepository.com/artifact/com.espertech/esper-compiler

**Comment by sumitjha4321** [comment]
@bernhardttom
This use-case has come up to change the EPL at runtime.

Say an EPL is running and for some reason, we need to update the statement's query. 
We currently do this by DESTROYING and RE-CREATING a new EPL with same name and query. But once we do that, we stop receiving "statementName" in metrics reported by engine as stated above.

Is there any other way we can do this (to update the statement at runtime) ?

**Comment by bernhardttom** [comment]
version 8.1: there is only undeploy and deploy
