### ISSUE TITLE
ConstantExpression generated wrong statement when constant is String and contains " (double quotes)

### ISSUE THREAD

**Issue by kaicao** [espertechinc/esper#162]
When using ConstantExpression to generate statement, and providing constant like 
```
some "value"
```
it generates statement without proper escaping of " (double quotes) and leads to wrong statement.
```
ConstantExpression ex = new ConstantExpression("some \"value\"");
    StringWriter writer = new StringWriter();
    ex.toPrecedenceFreeEPL(writer);
    System.out.println(writer.toString());
// prints "some "value"" instead of "some \"value\""
```
Example Statement created with issue and fail when compile:
```
Filter filter = Filter.create("Event", Expressions.eq("field", "some \"value\""));
    EPStatementObjectModel model = new EPStatementObjectModel();
    model.setSelectClause(SelectClause.createWildcard());
    model.setFromClause(FromClause.create(FilterStream.create(filter)));
    realEsperProvider.createStatement(model);

// generates select * from Event(field="some "value"")
```
With error like "EPCompileException: Incorrect syntax near 'value' expecting a closing parenthesis ')' but found an identifier"

**Comment by kaicao** [comment]
Sorry wrong issue

**Comment by kaicao** [comment]
It compiles if the statement can be generated like:
```
select * from Event(field="some \"value\"")
```

**Comment by raguessner** [comment]
It is up to application code to escape. There is also no un-escape in the direction of EPL string to EPStatementObjectModel.  
And escaping can be avoided here by single quotes '.

**Comment by kaicao** [comment]
Thank you for quick response, I will make the code to escape the string value before putting into Expression.
