### ISSUE TITLE
Provide api to get notification if errors occurred while receiving data from VirtualWindow

### ISSUE THREAD

**Issue by vndzzz** [espertechinc/esper#164]
Now all exception that are happening while data is retrieved in virtual window are logged only.  Consequently there is no way to know (except only reading logs ([source](https://github.com/espertechinc/esper/blob/release_8.2.0/common/src/main/java/com/espertech/esper/common/internal/epl/virtualdw/JoinExecTableLookupStrategyVirtualDW.java#L90))) that something is wrong (i.e. some external system, which provides data, failed)

It will be highly appreciated that some sort of Api exists to handle such cases.

**Comment by bernhardttom** [comment]
Make sure the app registers an exception handler.
Application code can rethrow exceptions as runtime exceptions or can raise an exception calling the internal API of ExceptionHandlingService (servicesContext)

**Comment by vndzzz** [comment]
@bernhardttom thanks for your reply. In external virtual windows only option is to use ExceptionHandlingService for handling described case.  It would be nice if it was described in documentation.
