### ISSUE TITLE
ESPER LIKE QUERY - CASE SENSITIVE

### ISSUE THREAD

**Issue by gadisridhar** [espertechinc/esper#17]
ESPER EPL LIKE QUERY IS CASE SENSITIVE. HOW DO I SOLVE IT. EX - select * from StockTick having symbol like '%YHOO%' . EVENTS HAVE SYMBOL AS 'yhoo'. GUYS SUGGEST. MANY THANKS

**Comment by bernhardttom** [comment]
apply uppercase or lowercase, either in the event getter method itself or register a user-defined function "toLowercase"
