### ISSUE TITLE
Regex parser handling of SLASH U character sequence

### ISSUE THREAD

**Issue by o-mdr** [espertechinc/esper#170]
Consider the following EPL and a matching event
```
select p00 regexp '.*\\user\\.*' as result from SupportBean_S0
new SupportBean_S0(-1, "\user\bob"));
```

We are trying to write a `regexp` to match a file path where the path contains `\user\` folder. Esper applies special parsing logic to `\u` treating this as a Unicode symbol.

A suggested fix for this is to detect when we are parsing a regexp and do NOT apply the `\u` logic. A naive fix for this and a test is available https://github.com/Inquisitive-Systems/esper/pull/1. Could someone please review this issue and a potential fix and let me know if this is something of interest to be accepted (modified and then accepted) by the upstream Esper repository? Thank you.

**Comment by bernhardttom** [comment]
What if you need to to use unicode. 
I suggest to rewrite the string.

**Comment by o-mdr** [comment]
I assume you talk about re-writing the regex string, what will be an alternative?

**Comment by bernhardttom** [comment]
rewriting it to use unicode instead would be one

**Comment by o-mdr** [comment]
So something like this `select p00 regexp '.*\\u0075ser\\.*' as result from SupportBean_S0`, where `\u0075` is unicode for `u`?
