### ISSUE TITLE
规则引擎决策树

### ISSUE THREAD

**Issue by xiangqingyijiu** [espertechinc/esper#178]
使用esper做规则引擎，能实现决策树这种吗

**Comment by bernhardttom** [comment]
Please post questions in English language.
Yes you can implement a decision tree using insert-into and split-stream.
The link to documentation http://esper.espertech.com/release-8.3.0/reference-esper/html_single/index.html#split_overview

**Comment by xiangqingyijiu** [comment]
does that work in esper 5.4.0 ?

**Comment by bernhardttom** [comment]
yes
