### ISSUE TITLE
Using java method with SELECT ... GROUP BY produces duplicated events.

### ISSUE THREAD

**Issue by ogibayashi** [espertechinc/esper#18]
In SELECT ... GROUP BY statement, if I use java method in SELECT clause, Esper produces resulting events for each incoming events. I expect one event produced for each group.

For example, I registered following query.

```
select str, str.split(',')as splitted, count(*) as cnt from 
```

and send this event 5 times.

```
{"str": "a,b,c"}
```

Then, I get 5 events.

```
{str=a,b,c, splitted=[Ljava.lang.String;@5c4e50a5, cnt=5}
{str=a,b,c, splitted=[Ljava.lang.String;@7bb01550, cnt=5}
{str=a,b,c, splitted=[Ljava.lang.String;@1c2181ce, cnt=5}
{str=a,b,c, splitted=[Ljava.lang.String;@21a417fc, cnt=5}
{str=a,b,c, splitted=[Ljava.lang.String;@f41b015, cnt=5}
```

Is this expected behavior? How can I get just one event for each group?

**Comment by bernhardttom** [comment]
see doc at http://espertech.com/esper/release-5.2.0/esper-reference/html_single/index.html#processingmodel_aggregation_output
this follows rel database behavior (those that allow this type of query)

**Comment by ogibayashi** [comment]
Thank you for your response. and sorry, EPL in my example was incomplete.

That should be
```
select str, str.split(',')as splitted, count(*) as cnt from TestString.win:time_batch(10 sec)  group by str
```
(I missed `TestString.win:time_batch(10 sec)  group by str`)

With this query, the output should be just one record for each `str`, but Esper returns same number of events as input events.

With relational database (e.g. MySQL) , records are aggregated and result in one record for the same group (this case, same `str` value).

```
mysql> select * from strtest;
+-------+
| str   |
+-------+
| 12345 |
| 12345 |
| 12345 |
| 12345 |
| 12345 |
+-------+

mysql> select str, substr(str, 1,2), count(*)  from strtest group by str;
+-------+------------------+----------+
| str   | substr(str, 1,2) | count(*) |
+-------+------------------+----------+
| 12345 | 12               |        5 |
+-------+------------------+----------+
```

With Esper, 

EPL similar to the above,

```
select str, str.substring(0,2) as substr, count(*) as cnt from TestString.win:time_batch(10 sec) "group by str
```

and events like `sendEvent(new TestStringEvent("12345"))` 5 times (`TestString` is a class that have just one `str` field) result in 5 events. I think these events should be aggregated becase they all have same `str` field value.

```
Event received: {str=12345, cnt=5, substr=12}
Event received: {str=12345, cnt=5, substr=12}
Event received: {str=12345, cnt=5, substr=12}
Event received: {str=12345, cnt=5, substr=12}
Event received: {str=12345, cnt=5, substr=12}
```

**Comment by bernhardttom** [comment]
"substr(str, 1,2)" is not the same as str.split(','), try "substr" in EPL instead

**Comment by ogibayashi** [comment]
I used "substr" example just to compare similar expression between EPL and SQL on MySQL. (Because we can't use "split" on MySQL). The point is that events are not aggregated by "GROUP BY" expression when I use java method in SELECT clause.

I tried to use "substr" in EPL, but  it seems that Esper does not provide such function. (Could not found in the documentation, and when I try in EPL, got error like "Unknown single-row function, expression declaration, script or aggregation function")

**Comment by ogibayashi** [comment]
BTW, I could use the function `firstever` to filter out unnecessary records and just receive single record per group. So, if the behavior above is expected, I will use this.

**Comment by bernhardttom** [comment]
MySQL doesn't have the concept of a method.
You can simply add the "substr" UDF as described in the docs so its the same as a MySQL function.

**Comment by ogibayashi** [comment]
Ah, I see. I should have create my own UDF instead of using java class.
I tried creating "substr" UDF and it worked as I expected. Thanks!
