### ISSUE TITLE
Documented google-groups mailing list doesn't appear correct

### ISSUE THREAD

**Issue by 0zeroth** [espertechinc/esper#188]
As documented: http://www.espertech.com/esper/mailing-list/
The provided 'Esper Usage Google Group' https://groups.google.com/forum/#!forum/esper-usage does not seem to exist, at least for me. Searching Google groups gives no hits. Similar for the NEsper Usage group.

Is there an active mailing list, and if so, where?

**Comment by bernhardttom** [comment]
I think you need to log into Google

**Comment by bernhardttom** [comment]
fixed

**Comment by 0zeroth** [comment]
I was logged in - today I hit the link and got the option to join straight away, so file under random glitch or user error. Thanks for your help.
