### ISSUE TITLE
Event Configuration ordering matters

### ISSUE THREAD

**Issue by NickWard** [espertechinc/esper#19]
Say you have 
* interface A
* class Event implements A

then A needs to be registered against Esper before the subclass 'Event' in order for it to work in statements. However, in com.espertech.esper.client.Configuration the event types are stored in a HashMap and then iterated over on engine start when they are actually introduced to the engine. In java 7 and previous to that it managed to Just Work (TM) although this is really a lucky coincidence. In java 8 the iteration order of HashMaps has been changed and so this fails. This obviously depends on the number of entries in the HashMap etc for the iteration order. If the ordering is not correct then you get errors such as:

```
Caused by: com.espertech.esper.epl.expression.core.ExprValidationException: Segmented context '[ContextName]' requires that any of the event types that are listed in the segmented context also appear in any of the filter expressions of the statement, type '[A]' is not one of the types listed
```

The maps in Configuration should be changed to LinkedHashMaps so that ordering can be maintained.

Cheers,
Nick

**Comment by bernhardttom** [comment]
not test case attached

**Comment by NickWard** [comment]
It's at minimum a 1 line change. It would take me longer to write and package the test case than it would take for you to just fix it.

**Comment by bernhardttom** [comment]
Since types can be registered various ways and just one possible way is by means of static configs its important to have the test case.
