### ISSUE TITLE
Enhance filter index building for reg-ex and other boolean-expressions that are independent of statement and partition

### ISSUE THREAD

**Issue by aewhite** [espertechinc/esper#191]
I was surprised to learn that when two statements are deployed that use identical regular expressions on the same field in the same event type triggered multiple executions of the regular expression matching logic. For a large number of regular expressions and/or for sufficiently complex expressions, this can be a performance bottleneck. 

The workaround is to create a `@public expression` that wraps the regex logic and then have both states reference that expression. However, it seems like the engine should handle this for you either by implementing some sort of value cache or by doing something like a common-term-extraction that I implemented by hand.

**Comment by bernhardttom** [comment]
Both "states"? 
I don't think the JVM compiler even does that for you?

**Comment by aewhite** [comment]
Both states -> both expressions. Basically, it seems like the engine should be able to do exactly what I did by hand.

**Comment by bernhardttom** [comment]
Can you please provide an example where it seems to not use a common evaluation?

**Comment by aewhite** [comment]
Sure:

```
final EPCompiler compiler = EPCompilerProvider.getCompiler();
final Configuration configuration = new Configuration();
configuration.getCommon().addEventType(Event.class);

final CompilerArguments compilerArguments = new CompilerArguments(configuration);
final String epl =
                "@name('test-a') select * from Event(url regexp '.*test.*');" +
                "@name('test-b') select * from Event(url regexp '.*test.*');";

final EPCompiled unit = compiler.compile(epl, compilerArguments);
final EPRuntime runtime = EPRuntimeProvider.getDefaultRuntime(configuration);
final EPDeployment deployment = runtime.getDeploymentService().deploy(unit);

runtime.getEventService().sendEventBean(new Event("http://test.com"), "Event");
```

Monitor `java.util.regex.Pattern#matcher` to see the multiple usages. The only way I've managed to get the system to only run the regex once was with code like this:

```
compiler.compile(
    "@public create expression isTestUrl { url => url regexp '.*test.*' }", 
    compilerArguments);
compilerArguments.getPath().add(isTestUrlUnit);
```

And then use EPL like `@name('test-a') select * from Event(isTestUrl(*));`

**Comment by bernhardttom** [comment]
Ok thanks for clarifying. The Java compiler also wouldn't do any such rewriting.

**Comment by aewhite** [comment]
Correct, the request/suggestion is that the engine builds a filter index or similar mechanism to memoize the result of regexes.

**Comment by bernhardttom** [comment]
Or one could just use insert-into.
insert into FilteredEvent(url regexp '.*test.*')
