### ISSUE TITLE
Failed to resolve event type error when using json schema

### ISSUE THREAD

**Issue by daniccan** [espertechinc/esper#192]
**Version of Esper:** 8.4.0

I am trying to use the esper library in a java application. 

When I use the following code, I get the error - `Failed to resolve event type, named window or table by name 'PersonEvent'`

```
EPCompiler epCompiler = EPCompilerProvider.getCompiler();
EPRuntime epRuntime = EPRuntimeProvider.getDefaultRuntime();

// Create Schema
String schemaModule = "@public @buseventtype create json schema PersonEvent(name string, age int);";
EPCompiled schemaCompiled = epCompiler.compile(schemaModule, null);
EPDeployment schemaDeployment = epRuntime.epDeploymentService().deploy(schemaCompiled);

// Deploy EPL Query
String epQuery = "@name('my-statement') select name, age from PersonEvent;"
EPCompiled queryCompiled = epCompiler.compile(epQuery, null);
EPDeployment queryDeployment = epRuntime.epDeploymentService().deploy(queryCompiled);

// Add Listener
EPStatement epStatement = epRuntime.getDeploymentService().getStatement(epDeployment.getDeploymentId(), "my-statement");
epStatement.addListener(new MyListener());
```

In the above code, I also confirmed that the Event Type exists using `epRuntime.getEventTypeService().getBusEventType("PersonEvent")`. Still the error gets thrown.

However, the following code works.

```
EPCompiler epCompiler = EPCompilerProvider.getCompiler();
EPRuntime epRuntime = EPRuntimeProvider.getDefaultRuntime();

// Create Schema + Deploy EPL Query
String schemaModule = "@public @buseventtype create json schema PersonEvent(name string, age int);";
String epQuery = "@name('my-statement') select name, age from PersonEvent;"
EPCompiled queryCompiled = epCompiler.compile(schemaModule + epQuery, null);
EPDeployment queryDeployment = epRuntime.epDeploymentService().deploy(queryCompiled);

// Add Listener
EPStatement epStatement = epRuntime.getDeploymentService().getStatement(epDeployment.getDeploymentId(), "my-statement");
epStatement.addListener(new MyListener());
```

The only difference between the two code snippets is that, in the second one, I am combining the schema and the query together to compile and deploy. Is this the only way to make this work? This would mean the schema has to be concatenated with every EPL query that is compiled and deployed.

**Comment by bernhardttom** [comment]
Please read up on compiler path. This is needed so the compiler knows the objects available.
http://esper.espertech.com/release-8.4.0/reference-esper/html_single/index.html#apicompiler-compilerarguments-path

**Comment by andre-fil** [comment]
> Please read up on compiler path. This is needed so the compiler knows the objects available. http://esper.espertech.com/release-8.4.0/reference-esper/html_single/index.html#apicompiler-compilerarguments-path

hi, i am a brazilian student. Can you help me please? I have a question regarding the EPN and I can't find a solution anywhere.
