### ISSUE TITLE
Can't use enum named 'NEW'

### ISSUE THREAD

**Issue by bernhardttom** [espertechinc/esper#2]
(issue migrated from http://jira.codehaus.org/browse/ESPER-812)

When using an imported enum which has an enum field called "NEW" then Esper does not parse the EPL code correctly. E.g. for the following on-expression:
on ExecutionEvent(status=ExecutionEventStatus.NEW) t
insert into AEvent
select t.status;
causes this exception:
"Caused by: com.espertech.esper.client.EPStatementSyntaxException: Incorrect syntax near 'NEW' (a reserved keyword) at line 1 column 46, please check the filter specification [on ExecutionEvent(status=ExecutionEventStatus.NEW) t"
This is tested on Esper 5.2.

**Comment by bernhardttom** [comment]
Version 5.3 will allow escaping with backticks like so: ExecutionEvent(status=ExecutionEventStatus.`NEW`)

**Comment by jheusser** [comment]
Same actually applies to enums of type LIMIT. E.g. `OrderType.LIMIT` does not parse correctly either.
