### ISSUE TITLE
clockInternal() not work after clockExternal()

### ISSUE THREAD

**Issue by yangguang760** [espertechinc/esper#200]
Issue:
epRuntime.clockExternal();
epRuntime.advanceTime(0);
epRuntime.getCurrentTime(); ==> 0
epRuntime.clockInternal();
epRuntime.getCurrentTime(); ==> 0
Thread.sleep(5000)
epRuntime.getCurrentTime(); ==> 0

Work around:
epRuntime.clockExternal();
epRuntime.advanceTime(0);
epRuntime.getCurrentTime(); ==> 0
epRuntime.advanceTime(System.currentMill);
epRuntime.clockInternal();
epRuntime.getCurrentTime(); ==> currentMill(t1)
Thread.sleep(5000)
epRuntime.getCurrentTime(); ==> currentMill(t1+5000ms)

Should advance to current time be called at the beginning of  clockInternal or we should add some explanation to clockInternal doc?

**Comment by bernhardttom** [comment]
Works fine for me. 
            Configuration configuration = new Configuration();
            configuration.getRuntime().getThreading().setInternalTimerEnabled(true);
            EPRuntime epRuntime = EPRuntimeProvider.getDefaultRuntime(configuration);
            EPEventService es = epRuntime.getEventService();
            es.clockExternal();
            es.advanceTime(0);
            assertEquals(0, es.getCurrentTime());
            es.clockInternal();
            assertEquals(0, es.getCurrentTime());
            Thread.sleep(5000);
            assertTrue(es.getCurrentTime() > 0);
