### ISSUE TITLE
Allow selecting from stream_def in On-Select

### ISSUE THREAD

**Issue by icholy** [espertechinc/esper#206]
Currently `On-Select` lets you select from a `window_or_table_name`.

```
on event_type[(filter_criteria)] [as stream_name]
[insert into insert_into_def]
select select_list
from window_or_table_name [as stream_name]
[where criteria_expression]
[group by grouping_expression_list]
[having grouping_search_conditions]
[order by order_by_expression_list]
```

It would be useful to extend this to the full `stream_def`

```
event_stream_name [(filter_criteria)] [contained_selection] [#window_spec] [#window_spec] [...]
```

This would enable queries like the following without having to declare a separate named window.

```
on QueryEvent select * from Orders#time(10 minutes)
```

**Comment by icholy** [comment]
I guess first `#window_spec` would have to be mandatory.

```
event_stream_name [(filter_criteria)] [contained_selection] #window_spec [#window_spec] [...]
```

**Comment by bernhardttom** [comment]
could also just use a subquery since they can return multiple rows

**Comment by icholy** [comment]
Are there technical reasons this isn't being considered? Or is it just not worth the effort because there's a work-around?

**Comment by bernhardttom** [comment]
on-select in the first place only exists as there is on-merge/update/delete - all of which require a table or named window and consistently on-select requires a table or named window. A join is probably preferred here as it adheres to SQL standards and is perhaps more readable and flexible.

**Comment by icholy** [comment]
It's just strange that select expressions are only limited in this context. It feels arbitrary and I assumed it was a bug until I looked it up in the docs. For what it's worth, I find `on-select` to be much easier to read than the equivalent join.

```
insert into SymbolCount
  select symbol, sum(qty) 
  from pattern[every timer:interval(5 sec)] unidirectional, 
       TickEvent#unique(symbol) t,
       NewsEvent#unique(symbol) as n 
  where t.symbol = n.symbol group by symbol

on pattern[every timer:interval(5 sec)]
  insert into SymbolCount
    select symbol, sum(qty)
    from TickEvent#unique(symbol) t,
         NewsEvent#unique(symbol) as n 
    where t.symbol = n.symbol group by symbol
```
