### ISSUE TITLE
WHERE-expression returning null when rewritten as filter negation lets filter pass when it should not

### ISSUE THREAD

**Issue by cyrilsochor** [espertechinc/esper#211]
I have EPL:
`select * from PersonEvent WHERE null = 'a'`

The WHERE condition `null = 'a'` successes in Esper 8.5.0 and a listener is activated!
In prior version 5.4.0 this condition fails and a listener isn't activated.

I thing that 5.4.0 behavior is correct - like in SQL.

**Comment by cyrilsochor** [comment]
There is a simple project which demonstrates the problem: [esper-simple.zip](https://github.com/espertechinc/esper/files/4966372/esper-simple.zip)

command: `gradlew run`
output:
```
Start
Name: Peter, Age: 10
Finish
```

when I change `versionEsper` from 8.5.0 to 8.4.0 in gradle.properties, the output is different:
```
Start
Finish
```

**Comment by hanusto** [comment]
Hi, do you have please update? We have the same problem.

**Comment by bernhardttom** [comment]
try configuration.getCompiler().getExecution().setFilterIndexPlanning(
    ConfigurationCompilerExecution.FilterIndexPlanning.BASIC);

**Comment by cyrilsochor** [comment]
Yes, esper 8.5 with setting FilterIndexPlanning.BASIC gives the same result as esper 8.4.
Why BASIC is not the default for backward compatibility?
Thank you.
