### ISSUE TITLE
Map with Collection as value seen as Object

### ISSUE THREAD

**Issue by streaming2936** [espertechinc/esper#214]
When there is an event type that has a Map field, the compiler won't allow enumeration functions such as `.anyOf`, as the values of the Map field are seen as Object.

Example:
```java
public class EventWithMapField {
    public EventWithMapField(Map<String, Collection<String>> strings) {
        this.strings = strings;
    }

    private final Map<String, Collection<String>> strings;

    public Map<String, Collection<String>> getStrings() {
        return strings;
    }
}
```
Using as follows:
```java
    public static void main(String[] args) {
        Configuration configuration = new Configuration();
        configuration.getCommon().addEventType(EventWithMapField.class);
        EPCompiled compiled;
        try {
            compiled = EPCompilerProvider.getCompiler().compile("select * from EventWithMapField(strings('a').anyOf(x => x like 'example-%'))", new CompilerArguments(configuration));
        } catch (EPCompileException ex) {
            throw new RuntimeException(ex);
        }
    }
```

Which results in 
>Caused by: com.espertech.esper.compiler.client.EPCompileException: Failed to validate filter expression 'strings("a").anyOf()': Invalid input for built-in enumeration method 'anyOf', expecting collection of event-type or scalar values as input, received class java.lang.Object [select * from EventWithMapField(strings('a').anyOf(x => x like 'example-%'))]

As the Map is typed, I would expect the compiler understands that anything coming from the Map is a collection so enumeration functions can be used. This behaviour is expected for dynamic properties as mentioned in the docs, but I couldn't find anything related to this. 

As a possible workaround I tried a `class StringList extends ArrayList<String>`as value class, but in that case the compiler won't let me use enumeration functions either. 

Casting works, but results in very messy EPL. Anything I'm missing here or can this be considered a bug/missing feature?

**Comment by bernhardttom** [comment]
There is no deep support for generics in version 8.5.0 because of Java type erasure. Generics support was added in version 8.6.0.
