### ISSUE TITLE
Downcasting from Object to BigDecimal incorrectly uses Number#longValue

### ISSUE THREAD

**Issue by Zoe-hz** [espertechinc/esper#217]
`            } else if (targetType.getType() == BigDecimal.class) {
                return (SimpleTypeCaster)(JavaClassHelper.isFloatingPointClass(fromType) ? SimpleTypeCasterFactory.BigDecDoubleCaster.INSTANCE : SimpleTypeCasterFactory.BigDecLongCaster.INSTANCE);
            } else {`

`    public static boolean isFloatingPointClass(Class<?> clazz) {
        return clazz == Float.class || clazz == Double.class || clazz == Float.TYPE || clazz == Double.TYPE;
    }`

**Comment by raguessner** [comment]
Without EPL I cannot understand what you are saying

**Comment by Zoe-hz** [comment]
Event class:
public class MyEvent {
   private Object[] params;
}

EPL:
select cast(params[0], BigDecimal) as money from MyEvent;

Decimal places will be lost in this case, because used BigDecLongCaster instead of BigDecDoubleCaster

**Comment by bernhardttom** [comment]
I think you are saying that downcasting from Object to BigDecimal incorrectly uses Number#longValue?

**Comment by Zoe-hz** [comment]
Yes

**Comment by icholy** [comment]
Possibly related to #202?
