### ISSUE TITLE
Version 5.2 - MemoryLeak in JoinSetComposerHistoricalImpl

### ISSUE THREAD

**Issue by vamsiganji** [espertechinc/esper#218]
We see JoinSetComposerHistoricalImpl referring java.util.LinkedHashSet and this is occupying 9GB of heap. We have a total of 16GB assigned to the process 

![image](https://user-images.githubusercontent.com/72225830/95768081-c1680180-0c83-11eb-9581-8225c315b857.png)

Version: 5.2.0

**Comment by raguessner** [comment]
Can you test and report please with a more recent version preferably 8.6.0? With 5.2 being 5 years old its a bit outdated.

**Comment by vamsiganji** [comment]
This is in production, so it is not possible to update the library at this time. Do you happen to know if this is a known issue fixed in some earlier release ?

**Comment by raguessner** [comment]
I have not found any information but my search wasn't comprehensive. The "changelog.txt" in the root folder is the main source.  Please post the EPL.
