### ISSUE TITLE
Question to concurrency and joins

### ISSUE THREAD

**Issue by panruipr** [espertechinc/esper#219]
I tried to join two timewindows using a left outer join，but sometimes the results are wrong
for example:
select * from leftEvent#time_batch(3 sec) as a left outer join rightEvent#time_batch(3 sec) as b on a.id = b.id

When the left window triggers, the right window sometimes has no data。For business reasons, I don't want to use #keepAll in the right window. Is there any other way?

**Comment by raguessner** [comment]
Use a context. Consult the documentation at [http://esper.espertech.com/release-8.6.0/reference-esper/html_single/index.html#view-batchwindows](url) 
You as well could substitute the batch with a #time(3 sec).

**Comment by panruipr** [comment]
I tried to solve this problem with context, but I failed。The code is as follows:

create context A1_003_Context partition by c_pool_code,c_stock_code,n_date from leftEvent,c_pool_code,c_sec_trade_code,n_date from rightEvent

select * from leftEvent#time(3 sec) as a left outer join rightEvent#time(3 sec) as b on a.c_pool_code= b.c_pool_code
and a.c_stock_code = b.c_stock_code and a.n_date = b.n_date

on the UpdateListener,There is no data in the right window in the log。
I looked at the usage of context, but I still didn't solve the problem.
This may be my use method is wrong, can you give me a simple example? thank you

**Comment by raguessner** [comment]
Maybe start at the beginning and tell us what the input is and the expected output? I'm clueless what you are trying to do. "correctness of left outer join"?

**Comment by panruipr** [comment]
This is test code:
` public class LeftJoinDemo {

    private static Logger logger = LoggerFactory.getLogger(LeftJoinDemo.class);

    public static void main(String[] args){
        logger.info("run left join demo");
        runDemo();

    }

    public static void runDemo(){

        Configuration configuration = new Configuration();

        Map<String,Object> leftEvent = new HashMap<>();
        leftEvent.put("leftId",int.class);
        leftEvent.put("leftName",String.class);
        leftEvent.put("leftCode",String.class);
        leftEvent.put("leftRemark",String.class);

        Map<String,Object> rightEvent = new HashMap<>();
        rightEvent.put("rightId",int.class);
        rightEvent.put("rightName",String.class);
        rightEvent.put("rightCode",String.class);
        rightEvent.put("rightRemark",String.class);

        configuration.getCommon().addEventType("leftEvent",leftEvent);
        configuration.getCommon().addEventType("rightEvent",rightEvent);

        EPRuntime epRuntime = EPRuntimeProvider.getDefaultRuntime(configuration);


        String epl = "select a.leftId      as leftId,\n" +
                "       a.leftName    as leftName,\n" +
                "       a.leftCode    as leftCode,\n" +
                "       b.rightName   as rightName,\n" +
                "       b.rightCode   as rightCode,\n" +
                "       b.rightRemark as rightRemark\n" +
                "  from leftEvent#time(3 sec) as a \n" +
                "  left outer join rightEvent#time(3 sec) as b \n" +
                "  on a.leftId = b.rightId\n" +
                "  and a.leftCode = b.rightCode";

        EPStatement epStatement = compileDeploy(epl, epRuntime);
        epStatement.addListener((newEvents, oldEvents, statement, runtime) -> {
            for (EventBean eventBean:newEvents){
                System.out.println(" leftId = " + eventBean.get("leftId") +
                            " leftName = " + eventBean.get("leftName") +
                            " leftCode = " + eventBean.get("leftCode") +
                            " rightName = " + eventBean.get("rightName") +
                            " rightCode = " + eventBean.get("rightCode") +
                            " rightRemark = " + eventBean.get("rightRemark")
                            );
            }
        });

        Map<String,Object> leftParams = new HashMap<>();
        leftParams.put("leftId",1);
        leftParams.put("leftName","left");
        leftParams.put("leftCode","001");
        leftParams.put("leftRemark","left context");
        epRuntime.getEventService().sendEventMap(leftParams, "leftEvent");

        Map<String,Object> rightParams = new HashMap<>();
        rightParams.put("rightId",1);
        rightParams.put("rightName","right");
        rightParams.put("rightCode","001");
        rightParams.put("rightRemark","right context");
        epRuntime.getEventService().sendEventMap(rightParams, "rightEvent");
    }

    private static EPStatement compileDeploy(String epl, EPRuntime runtime) {
        try {
            CompilerArguments args = new CompilerArguments();
            args.getPath().add(runtime.getRuntimePath());
            args.getOptions().setAccessModifierNamedWindow(env -> NameAccessModifier.PUBLIC); // All named windows are visibile
            args.getConfiguration().getCompiler().getByteCode().setAllowSubscriber(true); // allow subscribers
            args.getOptions().setAccessModifierContext(evn -> NameAccessModifier.PUBLIC);// all context are visibile
            EPCompiled compiled = EPCompilerProvider.getCompiler().compile(epl, args);
            EPDeployment deployment = runtime.getDeploymentService().deploy(compiled);
            return deployment.getStatements()[0];
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }

}`
Here is the log:
> leftId = 1 leftName = left leftCode = 001 rightName = null rightCode = null rightRemark = null
 leftId = 1 leftName = left leftCode = 001 rightName = right rightCode = 001 rightRemark = right context

It is obvious that the first data is wrong. The reason is when the leftevent arrives. Rightevent has not arrived yet. What I want to ask is how to ensure that rightevent has data when leftevent is triggered.

**Comment by raguessner** [comment]
From this post I still don't understand what the input is and the expected output. Show me the requirements and I can help you find a solution. Don't show me code or EPL.

**Comment by panruipr** [comment]
left outer join，

I expect that when the event on the left triggers the listening, the data on the right already exists.

**Comment by raguessner** [comment]
The code sends "leftEvent" first so that wouldnt be the case...

**Comment by panruipr** [comment]
But if you use threads to send data, you can't guarantee the order

**Comment by bernhardttom** [comment]
I think there is plenty of information in the documentation and solution patterns link https://www.espertech.com/esper/solution-patterns/
You could post to the user mailing list if you want to discuss more.
