### ISSUE TITLE
No output from statement with multiple regexp or like clauses for the same event property

### ISSUE THREAD

**Issue by frbor** [espertechinc/esper#233]
We're having problems with a statement with multiple REGEXP clauses. To replicate the issue I've created an esper notebook with these cells:

```sql
%esperepl

CREATE SCHEMA Event(timestamp long, domain string);

SELECT event 

FROM Event(
        domain REGEXP "test.*"
    AND domain NOT REGEXP ".*\\.gov"
    AND domain NOT REGEXP ".*\\.org"
) event
```

```
%esperscenario

Event = {domain="test.com"};
```

When running this notebook I **do not get any output events**, but if I remove **either one** of the _AND_ statements I get output.

I know that I can refactor this simple example using a single REGEXP, but I am puzzled why this breaks in the first place as I can not see any logical explanation.

We've tried the same code locally, and the statement works in Esper 8.4.0, but not in Esper 8.5.0 and higher.

**Comment by frbor** [comment]
We observe the same issue with the LIKE statement, do the example below does not match either (unless you remove one of statements:

```sql
SELECT event 
FROM Event(
    domain LIKE "%" AND domain LIKE "%"
) event
```

Again, this is a simplified example, but just shows that it seems to be a problem when matching with multiple LIKE or REGEXP?

**Comment by bernhardttom** [comment]
It may be an issue with filter index planning. Try setting the BASIC level of planning.

**Comment by frbor** [comment]
We tried setting FilterIndexPlanning.BASIC and indeed, that seems to mitigate the problem.

**Comment by kaicao** [comment]
Is there any updates on this issue? I managed to reproduce the same issue both locally and by the esper notebook example as @frbor provided.
