### ISSUE TITLE
Can not get data from update function on linux platform,but can get data on Windows platform.

### ISSUE THREAD

**Issue by angelyouyou** [espertechinc/esper#234]
The same code(see the attached file), caused different result.
Can not get data from update function on linux platform,but can get data on Windows platform.
The field "ipVer" is null on Linux platform.

**Linux(CentOS7):**
{pps=791.6666666666666, bps=280833.3333333333, dstcustcode=10052, **ipVer=null**,staddr=47924920282044996736654248843608588704, type=tcpack}

XFlow packet content:
 dstCustCode=10052
 routerName=Router-Test
 exportIp=192.168.66.212
 **ipVer=6**
 srcAddr=2409:8921:56a0:3aba:ddcd:fae0:535d:d6d7
 dstAddr=240e:ff:f101:10::1a0
 nextHope=fe80:0:0:0:0:0:0:0
 packets=2
 octects=1510
 InputInt=800
 OutputInt=818
 startTime=3972935152
 endTime=3972958552
 srcPort=50101
 dstPort=443
 tcpFlags=10000
 protocol=TCP
 tos=48
 srcAs=56046
 dstAs=4816
 srcMask=0
 dstMask=0

**Windows10:**
{"attackId":100000001,"custcode":"8",**"ipVer":4**,"direction":"Incoming","dstIp":"1.1.1.1","srcIp":"","srcaddr":0,"attackStatus":"ongoing","startTime":"2021-02-25 23:34:09","startTime_":"2021-02-25 23:34:09","duration":303062,"durationSec":303,"trafficRate":3005600000.00,"packetRate":3005600.00,"maxTrafficRate":24997480500.00,"maxPacketRate":24187808.30,"attackTypes":["icmp","iptraffic"],"attackTypesStr":"iptraffic,icmp","mainAttackType":"iptraffic","alarmLevel":3,"timestamp":1614267552062,"message":"攻击方式：iptraffic，使用阈值（低/高）：200.0 bps / 200.0 bps","unit":"bps","threshold":200.0,"country":"APNIC","province":"APNIC","city":"","carrier":"","detectTimes":23095}

[code and epl.zip](https://github.com/espertechinc/esper/files/6044119/code.and.epl.zip)

**Comment by raguessner** [comment]
Please provide code that I can run

**Comment by angelyouyou** [comment]
@raguessner sorry for it , it's my mistake. my .epl is not refred with code. I will close this issue.
