### ISSUE TITLE
Use Advanced Threading. How to Collect Results

### ISSUE THREAD

**Issue by zhuchaoyang1** [espertechinc/esper#239]
Use Advanced Threading,   In the case of concurrency, how does the main thread collect the results issued by Subscribe/Listener.

Looking forward to your reply. Thank you.

**Comment by raguessner** [comment]
You need to use your own application threadpool, queue, future or latch or whichever mechanism you prefer. Advanced threading doesn't have an API.

**Comment by zhuchaoyang1** [comment]
> You need to use your own application threadpool, queue, future or latch or whichever mechanism you prefer. Advanced threading doesn't have an API.

Thanks a lot

**Comment by zhuchaoyang1** [comment]
> You need to use your own application threadpool, queue, future or latch or whichever mechanism you prefer. Advanced threading doesn't have an API.

What is the meaning of advanced threads?
