### ISSUE TITLE
Event type that is registered, but not able to be triggered

### ISSUE THREAD

**Issue by kaicao** [espertechinc/esper#240]
Hi,

### Affected version
I'm running on Esper 8.4.0. Though the situation maybe similar for other versions.

### Issue description
It's related to Event types registered into Esper. That the statement on the parent class does not match, unless using fully qualified name of the parent.

### To reproduce
If you define class A and interface B which class A implements:
```
public class A implements B {
    public String value;
    @Override
    public String getValue() {
      return value;
    }
  }
public interface B {
    String getValue();
}
```
Next, register both A and B into Esper's configuration like
```
configuration.getCommon().addEventType("A", A.class);
configuration.getCommon().addEventType("B", B.class);
```
Then, create simple different statements to match on A and B, and create subscriber:
```
statement1: SELECT event FROM B(value = "value1") event;
statement2: SELECT event FROM A(value = "value1") event; 
```
If you send instance of A into Esper, the subscriber only trigger on statement2 which is matching against A, but it should match on both statements.
```
A instance = new A();
A.value = "value1";
getRuntime().getEventService().sendEventBean(instance,  null);
```

### Investigation
By debugging using unit tests, I found `EventTypeRepositoryImpl` which resolve the `nameToTypeMap` would register fully qualified name of B when class B is defined after A into configuration.
And if I switch the order of the event type registration, the `EventTypeRepositoryImpl` manage to resolve using provided `eventTypeName` for B.class, and also both statements above managed to match:
```
// make sure parent class is registered first 
configuration.getCommon().addEventType("B", B.class);
configuration.getCommon().addEventType("A", A.class);
```

### Summary
I looked into documentation of `addEventType` but it does not mention about the order of registration for the parent and child classes. 
So I'm not sure the solution is to always define the parent class first.
Please help!

**Comment by bernhardttom** [comment]
This is probably already in the documentation, did you check?

**Comment by kaicao** [comment]
I checked the document for same version of Esper, such as:
- Section 15.6.1 Compiler Configuration: http://esper.espertech.com/release-8.4.0/reference-esper/html_single/index.html#apicompiler-compilerarguments-configuration
- Section 17.4.3. Events Represented by Classes: http://esper.espertech.com/release-8.4.0/reference-esper/html_single/index.html#configuration-common-eventtypebean

As well as source code javadoc for `ConfigurationCommon.addEventType`: https://github.com/espertechinc/esper/blob/master/common/src/main/java/com/espertech/esper/common/client/configuration/common/ConfigurationCommon.java#L198

But I can't find any mentioning of how the parent classes were resolved and mapped, also that require to define the parent class first before define child classes (based on my test, but would need your confirmation).

Since the Esper documentation is rather large, I may have missed it, please help point out. 
Otherwise would be good to clarify when I need to define event type for a parent class, is it mandatory to have it registered before child classes.
