### ISSUE TITLE
Java8 lambdas and streams

### ISSUE THREAD

**Issue by jheusser** [espertechinc/esper#25]
Is there planned support for Java 8 lambda syntax and streams inside Esper? Or do you think the Enumeration Methods currently supported in Esper already fulfill that exact purpose?

It could be pretty powerful to expose a `Stream<ValueObject>` in Esper which is then queriable via normal stream methods such as:

```SQL
insert into OutputEvent
select * from UpdateEvent
where trackerVariable.stream().filter(p -> p.getValue() > 10);
```

but I realise this is kind of in conflict with the Enumeration Methods.

**Comment by bernhardttom** [comment]
Enumeration methods already provide that, i.e. "trackerVariable.where(p -> p.getValue() > 10)". The doc link is ttp://espertech.com/esper/release-5.3.0/esper-reference/html_single/index.html#enumerationreference.
