### ISSUE TITLE
EPDeployException: Deployment already exists by same-value crc

### ISSUE THREAD

**Issue by bimauniqqon** [espertechinc/esper#254]
we get error EPDeployException: Deployment already exists by same-value crc when deploy EPCompiled using this epl 

@name('rule-028427447#00013') select stock,board,time,bestBidPrice,bestOfferPrice from OrderFeed where stock = 'BBYB' and board = 'RG' and bestBidPrice = 1725.000000 and bestBidPrice > 0

we check no duplicate name rule.

using esper-compiler-8.1.0.jar

**Comment by bernhardttom** [comment]
Can you please test against the current version and provide a test class to reproduce the issue
