### ISSUE TITLE
size with pattern every-distinct and expiry

### ISSUE THREAD

**Issue by frbor** [espertechinc/esper#255]
I'm trying to get the total size of all events in a `every-distinct` statement with expiry, but the size continues to increase, so I'm unsure whether this is supported?

The following esper notebook illustrates the issue:

```sql
%esperepl
CREATE SCHEMA Event(signature string);
SELECT size
FROM PATTERN [EVERY-DISTINCT(
    signature,
    1 seconds
) event = Event]#size
```

inserting these events:
```
%esperscenario
t = "2021-11-02 11:00:00.000";
Event = {signature='scan'};
t = t.plus(0 minutes 1 seconds);
Event = {signature='scan'};
t = t.plus(0 minutes 1 seconds);
Event = {signature='scan'};
t = t.plus(0 minutes 1 seconds);
Event = {signature='scan'};
t = t.plus(0 minutes 1 seconds);
Event = {signature='scan'};
t = t.plus(0 minutes 1 seconds);
```

and yields the following output:
```
2021-11-02 11:00:00.000 stmt-1-output={size=1}
2021-11-02 11:00:01.000 stmt-1-output={size=2}
2021-11-02 11:00:02.000 stmt-1-output={size=3}
2021-11-02 11:00:03.000 stmt-1-output={size=4}
2021-11-02 11:00:04.000 stmt-1-output={size=5}
```

As you can se, `size` continues to grow, and I would expect this to stay a 1 or 2, since we have the expiry of `1 seconds`. Is there something wrong with my statement or have I misunderstood the documentation on size in combination with every-distinct? Or is it correct that the size here will continue to increase?

Using size in combination with a timed window, like this gives me the expected result:
```sql
SELECT size 
FROM Event#time(3 SEC)#size
OUTPUT SNAPSHOT EVERY 1 SECOND
```
```
2021-11-02 11:00:01.000 stmt-1-output={size=1}
2021-11-02 11:00:02.000 stmt-1-output={size=2}
2021-11-02 11:00:03.000 stmt-1-output={size=2}
2021-11-02 11:00:04.000 stmt-1-output={size=2}
2021-11-02 11:00:05.000 stmt-1-output={size=2}
```

best regards,
  
     Fredrik

**Comment by bernhardttom** [comment]
Its the count(*) aggregation you are looking for. "select count(*) from Event#unique(blah)#time(1)" for a count of the intersection of unique events not older than 1 sec, to make an example.

The #size view is not the same as a count. Patterns together with views process pattern matches. #size is for simple count up.
