### ISSUE TITLE
Possible memory leak in com.espertech.esper.runtime.internal.filtersvcimpl.FilterServiceLockCoarse

### ISSUE THREAD

**Issue by mycroft11** [espertechinc/esper#263]
Hi,

After running about a month, the FilterServiceLockCoarse seems to aquire many entries in the inner map. We use Esper 8.8.9 on jdk 11.

![image](https://user-images.githubusercontent.com/1137318/171173886-78557fa1-9e0f-477f-9304-0f02bce24a74.png)

**Comment by bernhardttom** [comment]
The typical things that leave filters behind are:
- context partitions not terminated
- deployments not undeployed
- patterns with filter subexpressions not bounded
- dataflows still running
If still having a question provide some detail
