### ISSUE TITLE
automatic incremental statement naming

### ISSUE THREAD

**Issue by DevDrake** [espertechinc/esper#264]
Hi,

I was porting an esper 5 application to esper 8. There is single problem i could not resolve, to behave as in old esper, all of the query names are "stmt-0". Is there a way to make it working in similar fashion as it was in older espers? 
e.g. "stmt-<incremental_number>" 

Thanks!

**Comment by bernhardttom** [comment]
Check under DeploymentOptions there is a StatementNameRuntimeOption that sets the statement name

**Comment by DevDrake** [comment]
Thanks

It looks that providing something like 
```
public static class StatementNameRuntimeOptionImpl implements StatementNameRuntimeOption {
    @Override
    public String getStatementName(final StatementNameRuntimeContext statementNameRuntimeContext) {
        return "stmt-" + statementNameRuntimeContext.getStatementId();
    }
}
```
gives similar results to esper pre 8. 

Then looking at statementId that is incremented for every deployment, does it mean that statementName being mostly stmt-0 (for not named statements) is a bug ? 
For me it looks that way. 

To have it behaves automatically with having option of using @name(<string>) we need to use string comparison of some kind with "guessed" automatic name like "stmt-0" doesn't seems perfect. It also look that it may behaves slight different when statement is partitioned.

**Comment by DevDrake** [comment]
What a significance statementId does have then ? 
Source of my confusion is that the statementId is disconnected from default statementName.

Custom naming works ok, but it's quiet strange how it is working internally. First @name or default name is applied and then as an option it can be overridden. The problem here is StatementNameRuntimeContext hasn't information what kind of name was provided to the statement (default or from @name).
