### ISSUE TITLE
License is confusing

### ISSUE THREAD

**Issue by survient** [espertechinc/esper#267]
The esper project includes a dual license of GPLv1 and GPLv2, but notes in the README that:

>Esper and NEsper are open-source software available under the GNU General Public License (GPL) version 2 (GPL v2).

>Esper and NEsper including documentation are copyrighted and the copyright is owned by EsperTech Inc., unauthorized reproduction or distribution of this copyrighted work is illegal.

These statements are conflicting and misleading. The project is not properly licensed under the GPLv1 or GPLv2 if the work is considered copyrighted such that the work cannot be redistributed in the manner outlined in the GPLv1 or GPLv2. If the copyright statement is referring to the names "Esper" and "NEsper" this is incorrect as the names can be trademarked but not marked as copyright. Additionally if the documentation for the project is considered copyright then the license for this should be clearly outlined as an additional license to the project or the documentation should be included as a separate, independently licensed project.

**Comment by bernhardttom** [comment]
Esper does NOT include a dual license of GPLv1 and GPLv2.

Where did you get the impression that Esper allows GPLv1?

See [page](https://www.espertech.com/esper/esper-license-and-trademark/) for license
