### ISSUE TITLE
Different #unique summarization based on order of events

### ISSUE THREAD

**Issue by dakotahNorth** [espertechinc/esper#271]
`#unique(field)` ensures that the `sum` is using the specified `field` when summing up the values. The following epl ...

        create schema StockTick(security string, price double);
        create schema OrderEvent (orderId int, trader string, symbol string, strategy string, 
        quantity double);

        select orderId, trader, symbol, strategy, sum(quantity) 
        from OrderEvent#unique(orderId) as o
        full outer join StockTick#lastevent as t 
        on o.symbol = t.security
        group by trader, symbol, strategy

Creates the following events:

        StockTick={security='IBM', price=99}
        OrderEvent={orderID=1, trader="A", symbol='IBM', strategy="VWAP", quantity=10}
        StockTick={security='IBM', price=99}

correctly provides the sum as sum(quantity)=10.0.

But, as in the order of events below, if the StockTick did not happen first:

      OrderEvent={orderID=1, trader="A", symbol='IBM', strategy="VWAP", quantity=10}
      StockTick={security='IBM', price=99}

The value of quantity should still be 10. But in this case it is `sum(quantity)`=20.0!!

This issue is also posted on StackOverflow ... https://stackoverflow.com/questions/73551428/unique-not-summing-up-correctly-based-on-order-of-events

**Comment by bernhardttom** [comment]
see docs on join and aggregation
