### ISSUE TITLE
OSGi + Java 11: Missing Constraints for apache xerces internal packages

### ISSUE THREAD

**Issue by Ulkusus** [espertechinc/esper#273]
Hello.

I am trying to use esper while extending an OSGi application targeting Java 11.

However, I can't seem to resolve the following constraints/imported packages stated in the esper-common MANIFEST.MF:

-  com.sun.org.apache.xerces.internal.dom,
-  com.sun.org.apache.xerces.internal.impl.dv.xs,
-  com.sun.org.apache.xerces.internal.xs

According to my research, these classes have been hidden/replaced with Java 9+, see:
[https://github.com/adoptium/adoptium-support/issues/199#issuecomment-717008260](url)

As there wasn't an obvious way to redirect or change these, I would appreciate ideas for solving this.
At least, it might make sense to mention this under the point on OSGi integration.

**Comment by bernhardttom** [comment]
included in 9.0.0
