### ISSUE TITLE
Esper 8.8.0/8.9.0 not compatible with hibernate 6.*.*

### ISSUE THREAD

**Issue by Prashant8976** [espertechinc/esper#278]
In latest spring boot applicarion , Esper 8.9.0 uses antlr 4.9.3 which is not working along with hibernate 6.2.* as it uses 4.10.1. Will esper 8.10.0 solve this issue ? When will you release it?

**Comment by bernhardttom** [comment]
Is there an exception when forcing the new ANTLR version?

**Comment by Prashant8976** [comment]
Hibernate 6.*.* adds antlr 4.10.1 jar 
For this esper fails with following error -
    ANTLR Tool version 4.9.3 used for code generation does not match with current runtime version 4.10.1
    ANTLR Tool version 4.9.3 used for parser compilation does not match with current runtime version 4.10.1
/

**Comment by Prashant8976** [comment]
### Hibernate 6.*.* adds Antlr-runtime 4.10.1 jar, So esper gives following error
    
Antlr tool version 4.9.3 used for code 
    generation does not match with current 
     runtime version 4.10.1
     Antlr tool version 4.9.3 used for parser 
     compilation does not match with current 
     runtime version 4.10.1  Java.io.invalidclassexception:org.antlr.v4.runtime.ATN; could not deserialize ATN with version 4(expected 3)


### If antlr-runtime 4.9.3 is used, after excluding it from hibernate, jpa annotations doesnt work, it gives following error-
Antlr tool version 4.10.1 used
generation does not match with current 
 runtime version 4.9.3
 Antlr tool version 4.10.1 used for parser 
 compilation does not match with current 
 runtime version 4.9.3
Error creating bean with name defined in 
 @EnableJpaRepositries declared on JpaRepositoriesRegistrar.EnableJpaRepositries.Coniguration:null
Java.io.invalidclassexception:org.antlr.v4.runtime.ATN; could not deserialize ATN with version 3(expected 4)

**Comment by bernhardttom** [comment]
ANTLR has information on this issue here: [https://github.com/antlr/antlr4/issues/3895](https://github.com/antlr/antlr4/issues/3895)
The script that regenerates the parser can be found in esper\compiler\grammar
We don't have a date yet when the new version ships, but it would probably ship with the current 4.13.x version of ANTLR.

**Comment by ggecy** [comment]
This also means that esper is incompatible with Spring boot 3, since it uses hibernate 6, which is a critical issue on our project which needs to be migrated urgently to spring boot 3 but it's blocked by esper.

**Comment by thomaskemmer** [comment]
Would be really good to get an update with the new ANTLR version soon. All newer Spring boot versions that still have OSS support require builds with the new ANTL to be compatible. 
For reference https://endoflife.date/spring-boot

**Comment by bernhardttom** [comment]
Changes are in version 9.0.0
