### ISSUE TITLE
Cannot invoke "...AggregationRowRemovedCallback.removedAggregationGroupKey(Object)" because "this.removedCallback" is null

### ISSUE THREAD

**Issue by kaicao** [espertechinc/esper#283]
Could you help us understand what can cause error of 
```
Cannot invoke "com.espertech.esper.common.internal.epl.agg.core.AggregationRowRemovedCallback.removedAggregationGroupKey(Object)" because "this.removedCallback" is null
```
For filter like:
```
INSERT INTO some_stream
SELECT customerID as customerID,
	   WINDOW(value1).distinctOf() as value1,
           value2,
           value3,
           min(startTime) AS minTimestamp,
           max(endTime) AS maxTimestamp
FROM Event(
 event.identifier IN ("Some identification")
).win:time(5 minutes) as event

GROUP BY customerID, value2, value3, event.getSomeBooleanValue()

HAVING SUM(count) > 0

OUTPUT SNAPSHOT EVERY 300 SECONDS
```

Esper 8.9.0 is in use.

**Comment by bernhardttom** [comment]
wasn't able to reproduce. Sample below
` env.advanceTime(0);
            String epl = "select p00, min(p01), max(p01) from SupportBean_S0#time(5) as s0 " +
                "group by p00, s0.getP02() " +
                "having sum(id) > 2" +
                "output snapshot every 5 sec";
            env.compileDeploy(epl);

            long current = 5000;
            for (int i = 0; i < 1000; i++) {
                env.sendEventBean(new SupportBean_S0(1, "a", "b", "c"));
                env.advanceTime(5000 * i);
            }

            env.undeployAll();`

**Comment by java30kcoding** [comment]
Same problem, did you resolve this?
My EPL is:
@Hint('reclaim_group_aged=60,reclaim_group_freq=60')
insert into temp_window
select
last(cast(values('timestamp'),long)) as timestamp,
last(cast(values('tags'),java.util.Map)) as tags,
window(cast(values('metric_value'), double)) as metricValues,
-- other fields omitted for brevity
from
FactEvent
#groupwin(values('objectId'))
#length(3)
group by
values('objectId');

When @Hint work then cause removedAggregationGroupKey NPE

**Comment by java30kcoding** [comment]
I try to modify ResultSetProcessorAggregateGroupedForge in version 8.3.0.
In function instanceCodegen() add one line:
instance.getServiceCtor().getBlock().exprDotMethod(MEMBER_AGGREGATIONSVC, "setRemovedCallback", ref("this"));

This resolve my problem.But I don't know is there another problem will occur by my way.
