### ISSUE TITLE
How to configure EPL statements to a separate file with .epl extension

### ISSUE THREAD

**Issue by h928725721** [espertechinc/esper#284]
hello:
it's my first time try to  use Esper.Now I want to move my Esper EPL statements from Java code to a separate file with the  extension ".epl" under the  resource directory of the SpringBoot project.But I don't know how to do it.
Are there any relevant documents for reference?

**Comment by bernhardttom** [comment]
Doc [link](http://esper.espertech.com/release-8.9.0/reference-esper/html_single/index.html#apicompiler-readingmodule)
