### ISSUE TITLE
Question: memory allocation of filter

### ISSUE THREAD

**Issue by kaicao** [espertechinc/esper#287]
Hi,

Thank you for the great work on Esper!

From time to time we have saw increasing of heap usage and GC when running multiple Esper filters. Thus hard to tell which filter(s) may have consumed more heap memory than others.

Is there anyway to get metrics regarding how much heap memory filter is using? 
If not easily achieved, any metrics to know count of items within window and how many partitions are created by the GROUP BY?
So that user can estimate whether its misbehaving or needs improvement on the statement code.

**Comment by bernhardttom** [comment]
There is a library and API that is part of Enterprise Edition that can report memory use as a breakdown.
