### ISSUE TITLE
Incorrect result for aggregation when multiple agg functions in same statement each take a declared expression as parameters and 

### ISSUE THREAD

**Issue by mstrobel** [espertechinc/esper#32]
One of our users reported to me that two expression-based columns in an Esper 5.3.0 query were producing identical values when the values should have been quite different.  When one column was commented out, the remaining column produced the expected values, but when both were present, the second column contained the same value as the first.

In this case, the two columns each contain a `sum` aggregation.  The operands of these `sum` aggregates are structurally similar, except that each one invokes a different lambda function.  The lambdas themselves are structurally similar, but not equivalent.

A simplified example is as follows:

    expression lambda1 { o => 1 * o.someValue } 
    expression lambda2 { o => 3 * o.someValue } 
    
    select sum(lambda1(e)) as value1
         , sum(lambda2(e)) as value2
      from SomeEvent as e

Given the query above, we expect `value1` and `value2` to contain `100` and `300` for an event having `someValue = 100`.  But Esper produces the same result for both:
      
value1 | value2
------ | ------
100 | 100

Esper has apparently determined that `sum(lambda2(e))` is equivalent to `sum(lambda1(e))` and substituted it in an attempt to reduce the number of aggregations computed.  Clearly, these expressions are not equivalent.

We can work around this by tweaking the structure of the `sum` operand for `value2` such that Esper no longer considers them equivalent.  For example, we can add `0` to the original operand:

    expression lambda1 { o => 1 * o.someValue } 
    expression lambda2 { o => 3 * o.someValue } 
    
    select sum(lambda1(e)) as value1
         , sum(lambda2(e) + 0) as value2
      from SomeEvent as e
      
The results for this query are what we *expected* to see for the first query.  Since Esper no longer incorrectly considers the two `sum` aggregations equivalent, we get the correct results:

value1 | value2
------ | ------
100 | 300

**Comment by bernhardttom** [comment]
merged changes into master for 5.4 release
