### ISSUE TITLE
Suggestion: update the build documentation and add automated builds to keep an eye on it

### ISSUE THREAD

**Issue by gigafone** [espertechinc/esper#35]
I've found that the [Building Esper](http://www.espertech.com/esper/building.php) documentation could be improved. When a project doesn't easily build *and* the documentation doesn't help, it leads to a bad developer experience.

I'm working my way through getting Esper's project-root maven build to work. As a minimal starting point, this is what I'm currently using:

```
mvn -DskipTests -Dgpg.skip=true install
```

I'd suggest this be added to the Esper documentation.

Also, I found in #34 that the build did not succeed for the current master.

Perhaps this situation could be improved by adding an automated build?

**Comment by gigafone** [comment]
One commit to help move this issue forward is here: https://github.com/gigafone/esper/commit/9f2eaf0c130890dc0c4474955d95884f5d6a953f

There is more to do after this. I recommend:

- [ ] test the build -- by hand -- on a fresh machine, from the perspective of an outside (e.g. non EsperTech) contributor
- [ ] setup automated builds

**Comment by bernhardttom** [comment]
updated "building" page at http://espertech.com/esper/building.php

We will look at why builds can fail in other environments.
