### ISSUE TITLE
Prior function does not accept constant variable

### ISSUE THREAD

**Issue by jheusser** [espertechinc/esper#41]
The following EPL results in the exception below
```
create constant variable int x = 10;
select prior(x, price) from Trade;
```

```
Caused by: com.espertech.esper.client.EPStatementSyntaxException: Incorrect syntax near 'x' at line 1 column 13, please check the select clause [select prior(x, price) from Trade]
```

Please close the issue if this is expected behaviour, but would have thought a variable (at least constant variable) could be used in this statement.

**Comment by bernhardttom** [comment]
How would the engine know how many prior events to retain?

**Comment by jheusser** [comment]
@bernhardttom as said, I don't know the internals, just was surprised a constant variable isn't accepted, then the engine could potentially know at compile time how many events to retain.
