### ISSUE TITLE
Cannot use reserved words as part of a property chain

### ISSUE THREAD

**Issue by LionelCons** [espertechinc/esper#45]
I have a class named "GROUP" with constants. I am trying to get something like "select GROUP.FOO as bar ..." working but I always get an error.

With:

    `GROUP`.FOO as bar

I get:

    Failed to validate select-clause expression '`GROUP`.FOO': Failed to resolve property '`GROUP`.FOO' to a stream or nested property in a stream

With:

    `GROUP.FOO` as bar

I get:

    Failed to validate select-clause expression 'GROUP.FOO': Property named 'GROUP.FOO' is not valid in any stream".

This seems to be the same problem as ESPER-686 (http://esper.13850.n7.nabble.com/jira-ESPER-686-Cannot-use-reserved-words-as-part-of-a-property-chain-td6666.html).

I am using Esper 5.3.0.

**Comment by bernhardttom** [comment]
Works for me.

`public class TestABC extends TestCase {
    public void test() {
        EPServiceProvider engine = EPServiceProviderManager.getDefaultProvider();
        engine.getEPAdministrator().getConfiguration().addEventType(MyEvent.class);

        engine.getEPAdministrator().createEPL("select `group`.id from MyEvent");
    }

    private static class MyEvent {
        private MyContainedEvent group;

        public MyContainedEvent getGroup() {
            return group;
        }

        public void setGroup(MyContainedEvent group) {
            this.group = group;
        }
    }

    private static class MyContainedEvent {
        private String id;

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }
}
`

**Comment by LionelCons** [comment]
The problem occurs (at least) when the reserved keyword is an enum.

I have patched TestPropertyResolution.java from master to reproduce the problem (see the attached files).

I get:
```
$ mvn test -Dtest=TestPropertyResolution
...
com.espertech.esper.epl.expression.core.ExprValidationException: Failed to validate filter expression 'group=`GROUP`.FOO': Failed to resolve property '`GROUP`.FOO' to a stream or nested property in a stream
...
```

[TestPropertyResolution.java.txt](https://github.com/espertechinc/esper/files/216493/TestPropertyResolution.java.txt)
[TestPropertyResolution.java.diff.txt](https://github.com/espertechinc/esper/files/216494/TestPropertyResolution.java.diff.txt)
