### ISSUE TITLE
User defined functions with varargs not recognized

### ISSUE THREAD

**Issue by LionelCons** [espertechinc/esper#47]
I am not able to use a user defined function with a variable number of arguments (called from EPL). I get: 

`com.espertech.esper.client.EPStatementException: Error starting statement: Failed to validate select-clause expression 'MapUtils.combine(l.extra,...(70 chars)': Failed to resolve 'MapUtils.combine' to a property, single-row function, aggregation function, script, stream or class name `

The function I am calling is: 

    public static Map<String, String> combine(final Map<String, String> ...maps) { 
        Map<String, String> result = new HashMap<String, String>(); 
        for (Map<String, String> map: maps) { 
            if (map != null) { 
                result.putAll(map); 
            } 
        } 
        return result; 
    } 

If OTOH I use this function instead: 

    public static Map<String, String> combine2(final Map<String, String> map1, 
                                               final Map<String, String> map2) { 
        return combine(map1, map2); 
    } 

Esper is happy.

**Comment by bernhardttom** [comment]
merged changes into master
