### ISSUE TITLE
esper (actually cglib) writes debug info to stderr

### ISSUE THREAD

**Issue by JerryShea** [espertechinc/esper#52]
I am seeing the below printed to stderr
hash=703891789 size=0
hash=703891789 size=0
... ...
when I run a particular query and this output is coming from FastMethod (see 
https://github.com/cglib/cglib/blob/master/cglib/src/main/java/net/sf/cglib/reflect/FastMethod.java and search for "System.err.println") which is called from com.espertech.esper.event.bean.DynamicPropertyGetterBase#getPopulateCache

**Comment by JerryShea** [comment]
cglib writes this before throwing an exception because it can't find the method so I guess this is not terribly important i.e. it will only happen for query that is about to throw an exception. Why it can't find the method and is throwing an exception is another matter, however...

**Comment by jheusser** [comment]
Also regarding cglib, sorry to hijack this issue, looks like the version used (3.1) is from 2013, an upgrade would probably be good if it's compatible.

**Comment by bernhardttom** [comment]
Between minor releases, i.e. 5.4 to 5.5, we need to keep the dependent jar files the same. The next cglib update would be version 6.
