### ISSUE TITLE
Help needed with a query and user defined function in Esper

### ISSUE THREAD

**Issue by UmerIftikhar** [espertechinc/esper#53]
I am trying to create an EPL statement that will show whether an order is possible or not.

There are two Events, EventA(processed) and EventB(non processed).

create schema EventA(type string, percentCompleted integer);
create schema EventB(type string);

The statement should match all processed elements, based on the type(string) of the element. The result should contain a Boolean value, which indicates whether an order should be processed or not.

I have got the statement below to return true when a successful match is made(and an order can be placed). However, I would also like to return a false when an order can not be placed.

Case tested here:
http://esper-epl-tryout.appspot.com/epltryout/mainform.html

   create schema EventA(type string, percentCompleted integer);  
   create schema EventB(type string);

   @Name('Out') select * from pattern [every a=EventA -> every  b=EventB(a.type = b.type AND a.percentCompleted > 20) ]
Sequence:

  EventA={type="1",percentCompleted=0}  
  EventA={type="2",percentCompleted=0}  
  EventA={type="1",percentCompleted=20}   
  EventA={type="1",percentCompleted=40}  
  EventB={type="1"}  
Result: (Only returns a true result):

  Out-output={a={EventA={type='1', percentCompleted=40}}, b={EventB={type='1'}}}
I want my statement to return TRUE and "type" instead of the whole result, and also I want the query to return FALSE and "type" when a.percentCompleted < 20.

**Comment by jheusser** [comment]
You will get more answers for user questions on the mailinglist: http://www.espertech.com/esper/mailinglist.php
