### ISSUE TITLE
Check that a property on an EventBean exists

### ISSUE THREAD

**Issue by jc064522** [espertechinc/esper#56]
Some of my EPL statements use `window(*)`. In the `EventListener` in `update(...)` I'd like to check `newEvents` to see if any of them have that property, using for example `newEvents[0].get("window(*)")`. But if this the property, in my case `window(*)`, doesn't exist then `EventBean` will throw a `PropertyAccessException`. 

What do you think about adding a `doesPropertyExist(String property)` method to `EventBean`? I'm happy to do this if you think it's a good idea. But maybe I should be approaching this problem from another direction.

**Comment by jheusser** [comment]
Maybe you could use the `StatementAwareUpdateListener` so you don't have to guess which statement the event was triggered by and directly know what properties should be available.

**Comment by jc064522** [comment]
How would I know if the statement uses a window? I could check the text but what if someone's commented it out? The `eventBeans` are the result of how the statement has been parsed and processed: in this scenario I can be sure `window` was used.

**Comment by bernhardttom** [comment]
The "getEventType()" returns the EventType and that has a "isProperty" and "getPropertyDescriptor".

**Comment by jc064522** [comment]
Thanks Tom. If the statement doesn't have the `window(*)` property then `isProperty` tries to resolve the property (via `doResolvePropertyGetter`) and throws the same exception. But I see there is a `getPropertyNames(...)` method on `EventType`, so I can check against that.
