### ISSUE TITLE
win:ext_timed uses open interval

### ISSUE THREAD

**Issue by unhit** [espertechinc/esper#60]
Documentation states that (chapter 13.3.4. Externally-timed window (win:ext_timed))

> If the time interval between the timestamp values is larger then the timer period parameter, then the algorithm removes all oldest events tail-first until the difference between the oldest and newest event is within the time interval.

This seems not to be true. Looking at [test case](https://github.com/espertechinc/esper/blob/master/esper/src/test/java/com/espertech/esper/view/window/TestExternallyTimedWindowView.java) we see ext_timed window is defined with 1000ms interval, but events are removed when difference of timestamps is >= 1000ms rather than just > 1000ms.

**Comment by bernhardttom** [comment]
For a 1-second window, when an event arrives at t0 it gets expired at t0+1sec - behavior is consistent across all data windows. Any suggestions for a doc update?
