### ISSUE TITLE
Can esper generate new stream according to the group by?

### ISSUE THREAD

**Issue by tttMelody** [espertechinc/esper#63]
can esper generate new stream according to the group by?each group a new stream.

**Comment by bernhardttom** [comment]
Questions are best asked on the user mailing list or StackOverflow, see http://espertech.com/esper/mailinglist.php

**Comment by tttMelody** [comment]
@bernhardttom thanks

**Comment by tttMelody** [comment]
http://stackoverflow.com/questions/41498805/how-to-describe-this-complex-scene-by-cep
@bernhardttom  can you  take a look at this question? thans very much.

**Comment by bernhardttom** [comment]
Make sure to post to either StackOverflow or mailing list and not both.

**Comment by tttMelody** [comment]
@bernhardttom  got it, thanks very much
