### ISSUE TITLE
Classloading does not work in OSGi

### ISSUE THREAD

**Issue by dpishchukhin** [espertechinc/esper#64]
Esper converts Classes into FQCN in Configuration[346:349] and looses class loader. It tries to load class again in EventAdapterServiceImpl[461:499] with wrong class loader.

This behavior throws ClassNotFoundException in OSGi.

**Comment by bernhardttom** [comment]
The "epService.getEPAdministrator().getConfiguration().addEventType(class)" avoids this issue.

**Comment by bernhardttom** [comment]
version 6 provides more control over classloading
