### ISSUE TITLE
Esper 5.4 java process High CPU usage

### ISSUE THREAD

**Issue by jainankit2474** [espertechinc/esper#66]
We have upgraded Esper from 4.9 to 5.4 version. With Esper 4.9 version we were facing Esper "out of memory" issue in our Application. Then we have upgraded Esper to 5.4.

The Esper "out of memory" issue has been fixed but now we are facing High CPU Usage problem with Esper 5.4. Also facing the same problem with Esper 5.5 version.

We are using Java 8 version in our system.

Please suggest, How do I investigate: What part of the application or what thread is causing High CPU Utilization? And why am I facing high CPU usage problem with Esper latest version?

**Comment by bernhardttom** [comment]
The EPL and the actual events that are coming is are the two factors that determine memory use and CPU, along with JVM settings. Please provide the EPL and describe the events arriving and JVM settings.

**Comment by jainankit2474** [comment]
Thanking for the response, based on your feedback, we reviewed our epl structure and found few issues.
