### ISSUE TITLE
AggregatorAvg does not recover from NaN input across window boundaries

### ISSUE THREAD

**Issue by jheusser** [espertechinc/esper#67]
Once `Double.NaN` is fed into a `avg(.)` aggregator method it will not recover from it even across sliding window boundaries. Example code attached reproducing the issue. Tested with 5.1.0 and 5.4.0. Probably affects most non-BigDecimal aggregators, unless this is expected behaviour?

https://gist.github.com/jheusser/bd85aef89510231252ef57bdb7803909

Producing output
```
1.0
1.5
2.0
NaN
NaN
NaN
NaN
```

**Comment by bernhardttom** [comment]
Aggregations are incrementally computed thereby this is expected.

**Comment by bernhardttom** [comment]
POSITIVE_INFINITY and NEGATIVE_INFINITY would be the same question. Recommend to plug in your own aggregation function that counts special values.

**Comment by jheusser** [comment]
Thanks that's right, only found it now documented in the reference doc.
