### ISSUE TITLE
issue with context

### ISSUE THREAD

**Issue by richapanwar** [espertechinc/esper#7]
Hi,

I am using context by hash something like below.

create context HashedByUserId as coalesce  consistent_hash(userId) from templateEvent granularity 240 preallocate

and i have around 100 queries like 

context HashedByUserId  select userId from templateEvent(feature in('a','b','c')) where isCheckMet(1234);
context HashedByUserId select userId from templateEvent(feature in('a1','b1','c1')) where isCheckMet(2222);
context HashedByUserId select userId from templateEvent(feature in('a','b','c')) where isCheckMet(3333);
context HashedByUserId select userId from templateEvent(feature in('a1','b1','c1')) where isCheckMet(4444);

and so on....... where every Query has a unique identifier passed to isCheckMet();

what we have noticed here is , when i do sendEvent(templateEvent) to esper engine, its executing around 240  times each of my 100 Queries.

thus i am getting isCheckMet() called 240 times for id 1234.
same for other event ids as well.

 If i change this granularity from 240 value to 300 , single query gets executed 300 times.
Can you please tell what could be wrong in context here?

I have tried putting granularity as 1 , it worked fine and query gets executed only once, but with this i am loosing parallel processing.

Note: consistent_hash(userId) is the hasking we are using which return an int value using consistent hashing algorithm

Thanks

**Comment by bernhardttom2** [comment]
Provide a as-simple-as-possible test class

**Comment by richapanwar** [comment]
with the test class its not reproducible, its happening only in production with around 1500 queries running on different types of events.

**Comment by richapanwar** [comment]
If you can provide me the hint on what could be wrong in partition, i can debug in that direction.

**Comment by bernhardttom** [comment]
we need a test class

**Comment by richapanwar** [comment]
I am not able to attach any file here, it accpets inly jpg , gif and PNG.
Can you please tell me how can i attach a txt file here?

**Comment by bernhardttom** [comment]
The test class can be uploaded to another place such as Dropbox and you can add the link here.
