### ISSUE TITLE
CreateEPL with same name as insert into stream doesn't work as expected

### ISSUE THREAD

**Issue by hectorg87** [espertechinc/esper#72]
I'm using Esper 5.4.0, Java 8 and 64 bits OS. If any more information about the environment is needed let me know.

Given the following statement called **"STREAM_NAME"**

`epServiceProvider.getEPAdministrator().createEPL("insert into STREAM_NAME select COUNT(*) from ... .win:time(1 min) output snapshot every 1 min", "STREAM_NAME");`

And then querying it on another statement, let's say, **"statement2"** that selects from **"STREAM_NAME"** as:
`epServiceProvider.getEPAdministrator().createEPL("SELECT * FROM STREAM_NAME.win:time(1 min) output snapshot every 1 min", "statement2");`

The **statement2** does not output the data correctly. Most of the time it doesn't output anything, and once in a while it does output something, but much less than the real `COUNT(*)`.

I believe there's some conflict and when trying to SELECT from **"STREAM_NAME"** because the INSERT INTO stream name is the same as the statement name.

Any ideas what could be happening here? Is there a limitation or restriction I'm not aware of about the STREAM_NAME in the insert into having to be different than any STATEMENT NAME?

**Comment by bernhardttom** [comment]
There is no limitation. Provide a very simple test class please. Remove all time stuff to make it simpler.

**Comment by hectorg87** [comment]
Hello @bernhardttom, I think the problem I explained has nothing to do with the name of the statement and the stream inserted into, I did however managed to find a test case of my real problem. "very simple test class" was difficult, I did my best. I'm attaching a zip file with a maven project, it can be executed with mvn test or from your IDE of choice. It needs Java 8.

Let me explain what I'm doing:

I have the following to EPLs:
```
insert into STREAM_NAME_INSERT 
select current_timestamp() as x2, datetime as x, COUNT(*) as totalCount, foo as foo 
from TestEventType.win:time(5 sec) 
output snapshot every 5 sec
```
and:
```
SELECT current_timestamp() as insertCurrent, * 
FROM STREAM_NAME_INSERT.win:time(5 sec) 
output snapshot every 5 sec
```

then, 100 events are sent

 in batches of 10 every 5 seconds, with a random sleep between each. 

The following behaviours are observed:
1. ALWAYS, the first event of the 100 is "lost", is never retrieved by the listener. (`foo0` is always lost)
2. ALWAYS, this first batch of 10 events inserted into `STREAM_NAME_INSERT` is "lost"  when selected in the second query. (`foo0-foo9` is always lost)
[esper-problem.zip](https://github.com/espertechinc/esper/files/916318/esper-problem.zip)

3. SOMETIMES, this last batch of 10 events inserted into `STREAM_NAME_INSERT` is "lost"  when selected in the second query.
4. ALMOST ALWAYS, at least one batch of 10 events inserted into `STREAM_NAME_INSERT` is "lost"  when selected in the second query (other than the first and the last).
5. NOT TOO OFTEN, but observed occasionally, in the first query some events in-between one output snapshot and the next are lost
6. The case in 2. sometimes gives the update a null in `newData` in `update(EventBean[] newData, EventBean[] oldData)` and sometimes the listener is not even called.

**Comment by bernhardttom** [comment]
That would seem normal behavior because output-snapshot outputs what is currently in the data window or otherwise iterable, and the data window would have already expired one or more events by the time that output-snapshot activates for output. For example: (a) event comes in 8:00:00am (b) At 8:00:05am one or more events get removed as they are now 5 seconds old (c) At 8:00:05am the output-snapshot outputs current data window contents which doesn't have the one or more expired events.
If you want to achieve some batching where events have to be a part of one or another batch, see http://www.espertech.com/esper/release-6.0.1/esper-reference/html_single/index.html#view-batchwindows
