### ISSUE TITLE
Different object types in an array and extracting with contained events.

### ISSUE THREAD

**Issue by sbuster** [espertechinc/esper#77]
I have a structure like the one defined below where the contained events in Data can be optional.  How can I specify a generic type because I don't know the type at runtime as it's optional?

My use case is I have an IoT type device sending in data and the contained type may or may not be passed in at a given point in time.  I want to write a query that can pull out any item and process it.

select typeof(Data @type(???))
from Asset

Asset {
   Data { [
      Location {lat,long},
      Fuel{amount,used},
      Power {amount,used}
    }]
}

**Comment by raguessner** [comment]
As long as you can make the events into EventBean instances using a script or code this should be easy. You can follow instructions at http://espertech.com/esper/release-6.0.1/esper-reference/html_single/index.html#epl-containedeventselect-arrayofevent
