### ISSUE TITLE
virtual data window with .win:length(x) does not eliminate old value after restart

### ISSUE THREAD

**Issue by wangpeibin713** [espertechinc/esper#79]
I have create virtual data window plugin loader according the document [ http://www.espertech.com/esper/release-6.1.0/esper-reference/html/extension.html#extension-virtualdw]

then I create a vdw using `create window MySampleWindow.sample:samplevdw().win:length(5) as SampleEvent`
before restart the esper service this window eliminate the old event and keep at most 5 event in it 

then I restart the esper service  when this window have `n` items 

the window does not eliminate old value before restart and keep at most 5 + n event in it

**Comment by wangpeibin713** [comment]
- create deployment


```createschema SampleEvent as (key1 string, key2 string, value1 int, value2 double);
create window MySampleWindow.sample:samplevdw().win:length(5) as SampleEvent;
on SampleEvent se insert into  MySampleWindow select * ;
` ``

- sent event 


```
SampleEvent={key=1}
SampleEvent={key=2}
SampleEvent={key=3}
SampleEvent={key=4}
SampleEvent={key=5}
SampleEvent={key=6}
```

- query

```
select * from MySampleWindow 
    key={2,3,4,5,6}
```

- restart esper service


- sent event  again


```
SampleEvent={key=7}
SampleEvent={key=8}
SampleEvent={key=9}
SampleEvent={key=10}
SampleEvent={key=11}
SampleEvent={key=12}
```
- query

```
select * from MySampleWindow 
    key={2,3,4,5,6, 8,9,10,11,12}


expected to be 
   key={8,9,10,11,12}
```

**Comment by bernhardttom** [comment]
A virtual data window replaces all data windows and does not allow intersection or union. I'll keep it open so the doc change if required gets made.

**Comment by wangpeibin713** [comment]
so a virtual data window does not allow ".win:length(x)" too ?

**Comment by bernhardttom** [comment]
right
