### ISSUE TITLE
Change default behavior of 'output last' without 'order by' such that events are *not* retained in memory

### ISSUE THREAD

**Issue by eirikur-as** [espertechinc/esper#83]
### Background and Motivation
When an EPL statement makes use of `output last`, esper will retain events in memory until the output condition is true, unless the `enable_outputlimit_opt` hint is present (see http://www.espertech.com/esper/release-6.1.0/esper-reference/html/epl_clauses.html#epl-output-runtime ). This can lead to out-of-memory errors if the output condition is rarely true, when events arrive at a high rate and when events have a large memory footprint.

EPL, like SQL and other declarative languages, should empower developers by allowing them to specify *what* they want without having to figure out *how*. The esper engine should find an efficient plan to satisfy the EPL statement. However, by retaining events in memory, esper runs the risk of exhausting memory resources. This is perplexing in the case of `output last`, as there's no apparent reason (to EPL authors) for keeping events that arrived before the last one.

### Solution Proposal
I propose to change the default behavior to be identical to what happens when `enable_outputlimit_opt`  is present for all statements that use `output last` without an `order by` clause. 

Optionally, a configuration option can be introduced to cause esper to fall back to the current behavior, in case there are clients that rely on it.

**Comment by bernhardttom** [comment]
Have you done any testing or a trade-off analysis?

**Comment by eirikur-as** [comment]
I have not performed a performance trade-off analysis. Your question implies that you believe that `enable_outputlimit_opt` may have a negative performance impact in certain situations. I can only speculate as to what those might be. Perhaps it's more efficient to do aggregations on batches rather than in an on-line manner. If that's the case, then perhaps some hybrid solution that retains a bounded amount of events would strike a balance between CPU and mem usage.

My point is that retaining events without bounds is dangerous. With `output last` it's also counter-intuitive to retain events. This combination makes it easy for an EPL author to shoot him/herself in the foot.

The absolute worst case scenario when events are retained is that you run out of memory and your application crashes. What's the absolute worst case scenario when only the last event is retained? A slight decrease in throughput?

**Comment by bernhardttom** [comment]
Why only for output-last? It seems the argument can be made for output-all for some or maybe all of the cases in doc@3.7.2.

**Comment by eirikur-as** [comment]
Fair point. I'm simply not all that familiar with the expected behavior of `output all` with fully aggregated queries.
In general, I'd propose not to retain events without bounds unless absolutely necessary. But that's probably a big ask.

**Comment by bernhardttom** [comment]
The changes for this are merged. Please review.
