### ISSUE TITLE
How to handle with the situation Join-Aggregation?

### ISSUE THREAD

**Issue by egraldlo** [espertechinc/esper#84]
Hi, How Esper handle with the problem, recompute the aggregation function based on the join emit data. For example, join will emit data followed by sum( ) aggregation. whether esper can handle with the situation? 
I think event processing sometimes is different from batch processing, SQL handle well with batch processing, but SQL can processing event ?

**Comment by bernhardttom** [comment]
Unidirectional joins recompute aggregations.
All other joins update aggregations incrementally via add/subtract driven by the joined insert and remove stream.
