### ISSUE TITLE
referencing window in context declared in different EPL module

### ISSUE THREAD

**Issue by jheusser** [espertechinc/esper#9]
In Esper 5.1, when I refer to a window within a context, where the window has been declared in another module (and without context) I get the following error:

`Caused by: com.espertech.esper.epl.expression.core.ExprValidationException: Cannot create on-trigger expression: Named window 'TheWindow' was declared with context 'null', please use the same context instead`

The EPL is:
`
context ContextA
on pattern [ OtherEvent ]
insert into SomeEvent
select * from TheWindow;
`

That should be possible according to the doc at 4.6 saying
_Named windows are globally-visible data window that may be referred to by multiple statements. You may refer to named windows in statements that declare a context without any special considerations._

When I change the EPL without the on-trigger expression, then the expression compiles, e.g.
`
context ContextA
insert into SomeEvent
select tw.* from TheWindow tw, pattern [timer:interval(0)] unidirectional;
`

**Comment by bernhardttom** [comment]
version 5.3 will have updated docs
