### ISSUE TITLE
Using 'output first every 1 hour' with a particular pattern produces fewer results than expected

### ISSUE THREAD

**Issue by eirikur-as** [espertechinc/esper#90]
The following EPL statement only outputs the first ever event that is matched by the pattern. Matching events that arrive more than an hour later are not returned.
```
SELECT
  triggerEvent.sensorId,
  triggerEvent.value
FROM PATTERN [EVERY triggerEvent=SensorEvent(value > warningThreshold)
  -> (timer:interval(30 SECONDS) AND NOT disarmingEvent=SensorEvent(value <= warningThreshold))]
OUTPUT FIRST EVERY 1 HOUR
```

I've tested with esper 6.1.0 and 7.0.0-beta3 and both appear affected. Code that reproduces this issue is available in this [gist](https://gist.github.com/eirikur-as/8796241e90db7ddc0c2ba62fb94e618e).

**Comment by bernhardttom** [comment]
Set a time before creating any statement.

**Comment by eirikur-as** [comment]
I've tried setting a time before creating the statement. It doesn't change anything. Results are still the same.
Updated gist is [here](https://gist.github.com/eirikur-as/8796241e90db7ddc0c2ba62fb94e618e).
