### ISSUE TITLE
select insert question

### ISSUE THREAD

**Issue by yangguang760** [espertechinc/esper#96]
Hi all, 
I have a question here, if the only insert stream to the engine is A.
B and C are streams generated from 

``
insert into B
select x from A;
insert into C
select y from A;
``
Stream D are based on previous D, B and C independently, like
``
insert into D
select B.x,D.z+1 from B unidirectional,
D#lastevent
``
``
insert into D
select C.y,D.z+1  from C unidirectional,
D#lastevent
``

The question is , if D.z is 0 initially,and after a A fired, D.z is 1, but 2 is expected.
Anyone who can help? 
thx

**Comment by yangguang760** [comment]
update:
The example using EPL Online(http://esper-epl-tryout.appspot.com/epltryout/mainform.html)

EPL:
``
create schema StockTick(symbol string, price double);

create schema aPrice(price double);

insert into aPrice
select price from StockTick;

create schema bPrice(price double);

insert into bPrice
select price from StockTick;

create schema totalPrice(price double);

insert into totalPrice
select a.price+b.price as price from totalPrice#lastevent as a,bPrice as b unidirectional;

insert into totalPrice
select a.price+b.price as price from totalPrice#lastevent as a,aPrice as  b unidirectional;
@Name('Out') select * from totalPrice;
``

Time and event:
``
totalPrice={price=1}

t=t.plus(5 seconds)

StockTick={symbol='YHOO', price=65}
``

output:
``
At: 2001-01-01 08:00:00.000
Statement: Out
Insert
totalPrice={price=1.0}
At: 2001-01-01 08:00:05.000
Statement: Stmt-3
Insert
aPrice={price=65.0}
Statement: Stmt-5
Insert
bPrice={price=65.0}
Statement: Stmt-7
Insert
totalPrice={price=66.0}
Statement: Stmt-8
Insert
totalPrice={price=66.0}
Statement: Out
Insert
totalPrice={price=66.0}
Insert
totalPrice={price=66.0}
``

How can I make the totalPrice to be 1+65+65=131 ?

**Comment by bernhardttom** [comment]
I think what you are asking is how to make a 1-event session or partition, where a single event is both the start and the end of the analysis and this 1-event session needs multiple EPL statements to build up state. This is best done by sending "StockTickStart" and "StockTickEnd" and with context partitions.

**Comment by yangguang760** [comment]
Thx for the help. Still confusing.
Exactly What I mean is, 
``
create schema OriginEvent(price double);
create schema EventA(price double);
create schema EventB(price double);
create schema EventAB(price double);
``
1. Event A and Event B are generated from OriginEvent
``
insert into EventA
select price+1 as price from OriginEvent;

insert into EventB
select price+1 as price from OriginEvent;
``

2. Event AB is generated from the (previous Event AB join EventA unidirectional),  (previous Event AB join EventB unidirectional)
``
insert into EventAB
select ab.price+a.price as price from EventAB#lastevent as ab,EventA as a unidirectional;

insert into EventAB
select ab.price+b.price as price from EventAB#lastevent as ab,EventA as b unidirectional;
``
3. Suppose there is already a EventAB0 before OriginEvent , what I expect are two EventAB,the first (EventAB1) with the state from EventA and EventAB0, and the second with the state from EventB and the EventAB1)
``
EventAB={price=1.0} EventAB={price=2.0}
``
4. Actually, the engine generated two EvnetAB, the  first with the state from EventA and EventAB0, and the second with the state from EventB and Event AB0
``
EventAB={price=1.0} EventAB={price=1.0}
``

**Comment by bernhardttom** [comment]
Please read this...
http://esper.espertech.com/release-7.0.0/esper-reference/html_single/index.html#api-processingorder
for the background information that you may need to have.

In step 2, the two statements are identical, is that on purpose?

In step 3, maybe actually provide the input events?

What is the actual requirement? I don't have them. We are discussing why a particular piece of code behaves a certain way and I don't even have the input.........
