### ISSUE TITLE
Using initiated by pattern objects in terminate phase

### ISSUE THREAD

**Issue by sbuster** [espertechinc/esper#98]
Per the post on groups.google.com, using the 'as' keyword with pattern within a context to reference an object in the initiated clause in terminated by clause.

create context StockTick
initiated by pattern[a=StockTick] as starter
terminated by pattern[StockTick(symbol=starter.symbol)]

fails when using 'as' keyword, but works without it.

**Comment by bernhardttom** [comment]
The "as" keyword for patterns is not part of the grammar. It could be added however it would make expressions longer. The right expression would be actually be "starter.a.symbol" and "starter.symbol" is incorrect as it doesn't have the pattern tag "a" which is needed to identify events within the pattern i.e. "a=A -> b=B".
